import 'package:flutter/material.dart';

import '../../../core/app_colors.dart';
import '../../../core/common_widgets.dart';

// ---------------------------------------------------------------------------
// MODEL MATERI (sumber: Buku KIA 2024, disimpan di aplikasi, bisa dibaca offline)
// ---------------------------------------------------------------------------
enum _Jenis { subjudul, paragraf, poin, penting }

class _Blok {
  final _Jenis jenis;
  final String teks;
  const _Blok(this.jenis, this.teks);
}

class _Bab {
  final String judul;
  final String ringkasan;
  final IconData ikon;
  final List<_Blok> isi;
  const _Bab(this.judul, this.ringkasan, this.ikon, this.isi);

  String get teksCari => '$judul $ringkasan ${isi.map((b) => b.teks).join(' ')}'.toLowerCase();
}

const _sub = _Jenis.subjudul;
const _par = _Jenis.paragraf;
const _pnt = _Jenis.poin;
const _pen = _Jenis.penting;

const List<_Bab> _daftarBab = [
  // ========================= PERJALANAN IBU =========================
  _Bab(
    '1000 Hari Pertama & Kehamilan',
    'Masa paling penting bagi tumbuh kembang anak',
    Icons.pregnant_woman,
    [
      _Blok(_par,
          'Seribu hari pertama kehidupan (1000 HPK) adalah masa paling penting dalam pertumbuhan dan perkembangan anak. Masa ini terdiri dari 270 hari selama bayi di dalam kandungan, dan 730 hari atau dua tahun pertama setelah lahir.'),
      _Blok(_par,
          'Di dalam kandungan terbentuk organ penting seperti otak, jantung, hati, ginjal, paru-paru, dan tulang. Kekurangan gizi pada masa ini dapat menyebabkan gangguan tumbuh kembang, penyakit tidak menular, terhambatnya kemampuan berpikir, dan stunting (tubuh pendek).'),
      _Blok(_sub, 'Yang akan dialami'),
      _Blok(_pnt, 'Berat badan ibu naik sekitar 5-18 kg selama 9 bulan, sesuai status gizi ibu sebelum hamil.'),
      _Blok(_pnt, 'Usia kehamilan 1-3 bulan: bayi sebesar jeruk nipis di akhir bulan ke-3.'),
      _Blok(_pnt, 'Usia kehamilan 4-6 bulan: bayi sebesar jagung di akhir bulan ke-6.'),
      _Blok(_pnt, 'Usia kehamilan 7-9 bulan: bayi sebesar semangka di akhir bulan ke-9.'),
      _Blok(_sub, 'Yang harus dilakukan'),
      _Blok(_pnt, 'Segera periksa ke fasilitas kesehatan jika terlambat datang bulan 1 minggu.'),
      _Blok(_pnt, 'Periksa kehamilan paling sedikit 6 kali oleh dokter atau bidan.'),
      _Blok(_pnt, 'Makan lebih banyak atau lebih sering daripada sebelum hamil, dan cukup minum.'),
      _Blok(_pnt, 'Batasi kopi, teh, dan minuman bersoda. Hindari alkohol.'),
      _Blok(_pnt, 'Hindari merokok dan paparan asap rokok.'),
      _Blok(_pnt, 'Minum tablet tambah darah (TTD) atau multivitamin setiap hari selama kehamilan.'),
      _Blok(_pnt, 'Jangan minum obat yang tidak diresepkan dokter.'),
      _Blok(_pnt, 'Kenali tanda bahaya dan segera ke rumah sakit jika dirujuk.'),
      _Blok(_sub, 'Mengapa harus dilakukan'),
      _Blok(_pnt, 'Mencegah masalah pada kehamilan.'),
      _Blok(_pnt, 'Agar bayi lahir cukup bulan (38-40 minggu) dengan berat lahir paling sedikit 2,5 kg dan panjang paling sedikit 48 cm.'),
      _Blok(_pnt, 'Mempersiapkan ibu dan keluarga untuk kehamilan, melahirkan, dan perawatan bayi baru lahir.'),
      _Blok(_sub, 'Layanan kesehatan gratis selama kehamilan'),
      _Blok(_pnt, 'Pemeriksaan kehamilan oleh dokter, bidan, dan tenaga kesehatan.'),
      _Blok(_pnt, 'Tablet tambah darah atau multivitamin.'),
      _Blok(_pnt, 'Pemeriksaan status gizi, tekanan darah, dan laboratorium.'),
      _Blok(_pnt, 'Skrining kesehatan jiwa dan pemeriksaan kondisi bayi.'),
      _Blok(_pnt, 'Imunisasi tetanus, USG 2 kali, dan kelas ibu hamil.'),
      _Blok(_pen, 'Menjaga kesehatan sejak hamil adalah kunci mencegah stunting.'),
    ],
  ),
  _Bab(
    'Kehamilan Trimester 1',
    'Usia kehamilan 1-3 bulan',
    Icons.child_care,
    [
      _Blok(_par,
          'Selama 3 bulan pertama, ibu dan bayi mengalami berbagai perubahan. Ini adalah masa penting pembentukan bagian tubuh janin.'),
      _Blok(_sub, 'Yang akan dialami ibu'),
      _Blok(_pnt, 'Mual, muntah, dan mudah lelah. Pada masa ini rentan terjadi keguguran.'),
      _Blok(_pnt, 'Berat badan naik sekitar 1-3 kg.'),
      _Blok(_sub, 'Yang akan dialami bayi'),
      _Blok(_pnt, 'Tumbuh dari sebesar biji beras (0,64 cm) hingga sekitar 10 cm dan 28 gram, sebesar jeruk nipis.'),
      _Blok(_pnt, 'Bagian tubuh bayi, termasuk otak, mulai terbentuk.'),
      _Blok(_sub, 'Yang harus dilakukan'),
      _Blok(_pnt, 'Periksa kehamilan ke dokter paling sedikit satu kali, termasuk USG dan laboratorium lengkap.'),
      _Blok(_pnt, 'Makan porsi lebih kecil tapi sering: 3 kali makanan utama dan 2 kali makanan selingan.'),
      _Blok(_pnt, 'Minum TTD atau multivitamin setiap hari selama kehamilan.'),
      _Blok(_pnt, 'Kenali tanda bahaya. Jika mengalaminya, segera ke fasilitas kesehatan.'),
      _Blok(_sub, 'Cara minum TTD/MMS yang benar'),
      _Blok(_pnt, 'Minum setiap hari selama kehamilan untuk mencegah kekurangan darah.'),
      _Blok(_pnt, 'Sebaiknya malam hari sebelum tidur untuk mengurangi rasa mual.'),
      _Blok(_pnt, 'Minum bersama makanan atau minuman yang mengandung vitamin C, seperti buah, agar zat besi terserap lebih baik.'),
      _Blok(_pnt, 'Hindari minum bersama teh, kopi, susu, dan obat maag karena menghambat penyerapan zat besi.'),
      _Blok(_sub, 'Mengapa harus dilakukan'),
      _Blok(_pnt, 'Memastikan kesehatan ibu dan perkembangan bayi.'),
      _Blok(_pnt, 'Agar bisa dirawat segera jika ditemukan kondisi yang membahayakan ibu dan bayi.'),
      _Blok(_pen, 'Aktivitas fisik di trimester 1: pemanasan, peregangan, senam panggul, dan pendinginan.'),
    ],
  ),
  _Bab(
    'Kehamilan Trimester 2',
    'Usia kehamilan 4-6 bulan',
    Icons.child_friendly_outlined,
    [
      _Blok(_par, 'Saatnya mulai merencanakan kelahiran bersama tenaga kesehatan.'),
      _Blok(_sub, 'Yang akan dialami ibu'),
      _Blok(_pnt, 'Gejala awal kehamilan mulai berkurang.'),
      _Blok(_pnt, 'Berat badan naik sekitar 4-8 kg sesuai status gizi sebelum hamil.'),
      _Blok(_pnt, 'Mulai merasakan gerak bayi (menendang) pada usia kehamilan sekitar 5 bulan.'),
      _Blok(_sub, 'Yang akan dialami bayi'),
      _Blok(_pnt, 'Fungsi organ dan tubuh berkembang. Bayi tumbuh dari sekitar 12,5 cm (sebesar apel) hingga 34 cm dan sekitar 1000 gram (sebesar jagung) di akhir bulan ke-6.'),
      _Blok(_sub, 'Yang harus dilakukan'),
      _Blok(_pnt, 'Periksa kehamilan ke dokter atau bidan paling sedikit dua kali.'),
      _Blok(_pnt, 'Pantau gerak bayi.'),
      _Blok(_pnt, 'Makan porsi lebih kecil tapi sering: 3 kali makanan utama dan 1-2 kali kudapan.'),
      _Blok(_pnt, 'Minum TTD atau multivitamin setiap hari.'),
      _Blok(_pnt, 'Mulai merencanakan proses melahirkan melalui diskusi dengan tenaga kesehatan.'),
      _Blok(_sub, 'Mengapa harus dilakukan'),
      _Blok(_pnt, 'Memastikan ibu tetap sehat dan pertumbuhan bayi sesuai tahapannya.'),
      _Blok(_pnt, 'Agar keluarga sudah memiliki rencana melahirkan sejak jauh hari.'),
      _Blok(_pen, 'Segera periksa ke Puskesmas atau rumah sakit bila ada tanda bahaya (lihat bab Tanda Bahaya pada Kehamilan).'),
    ],
  ),
  _Bab(
    'Kehamilan Trimester 3',
    'Usia kehamilan 7-9 bulan dan persiapan melahirkan',
    Icons.event_note_outlined,
    [
      _Blok(_par,
          'Sebentar lagi ibu, ayah, dan keluarga bertemu anggota keluarga baru. Persiapan sebaiknya dilakukan jauh-jauh hari, mulai trimester kedua.'),
      _Blok(_sub, 'Yang akan dialami ibu'),
      _Blok(_pnt, 'Sering lelah, tidak nyaman, dan sulit tidur.'),
      _Blok(_pnt, 'Sering buang air kecil dan kaki bengkak.'),
      _Blok(_pnt, 'Berat badan naik sekitar 4-8 kg sesuai status gizi sebelum hamil.'),
      _Blok(_sub, 'Yang akan dialami bayi'),
      _Blok(_pnt, 'Organ memasuki tahap akhir dan bayi siap dilahirkan.'),
      _Blok(_pnt, 'Tumbuh dari panjang 40 cm dan sekitar 1300 gram (sebesar pepaya) hingga paling sedikit 48 cm dan sekitar 2500-3999 gram (sebesar semangka).'),
      _Blok(_sub, 'Yang harus dilakukan'),
      _Blok(_pnt, 'Periksa kehamilan paling sedikit tiga kali, salah satunya oleh dokter, termasuk USG dan laboratorium.'),
      _Blok(_pnt, 'Makan porsi kecil tapi sering: 3 kali makanan utama dan 1-2 kali kudapan.'),
      _Blok(_pnt, 'Minum TTD atau multivitamin setiap hari.'),
      _Blok(_pnt, 'Kenali tanda awal melahirkan dan tanda bahaya saat melahirkan.'),
      _Blok(_pnt, 'Pelajari proses melahirkan, pentingnya IMD dan ASI, serta perawatan bayi baru lahir.'),
      _Blok(_pnt, 'Diskusikan metode KB yang akan dipilih dengan tenaga kesehatan.'),
      _Blok(_sub, 'Daftar persiapan melahirkan'),
      _Blok(_pnt, 'Tanyakan kepada bidan atau dokter perkiraan tanggal melahirkan.'),
      _Blok(_pnt, 'Siapkan KTP, Kartu Keluarga, dan keperluan lain untuk ibu dan bayi.'),
      _Blok(_pnt, 'Minta suami atau keluarga mendampingi saat periksa dan melahirkan.'),
      _Blok(_pnt, 'Siapkan lebih dari 1 orang bergolongan darah sama yang bersedia menjadi pendonor bila diperlukan.'),
      _Blok(_pnt, 'Siapkan tabungan atau dana cadangan.'),
      _Blok(_pnt, 'Siapkan kendaraan bila sewaktu-waktu diperlukan.'),
      _Blok(_pnt, 'Miliki Kartu JKN dan daftarkan ke BPJS Kesehatan atau tanyakan ke petugas Puskesmas.'),
      _Blok(_pnt, 'Sepakati amanat persalinan dalam stiker P4K dan tempel di depan rumah.'),
      _Blok(_pnt, 'Rencanakan melahirkan oleh bidan atau dokter di Puskesmas, rumah sakit, atau klinik bersalin.'),
      _Blok(_pnt, 'Rencanakan ikut KB setelah bersalin.'),
      _Blok(_sub, 'Mitos dan fakta'),
      _Blok(_par,
          'Mitos: minyak dan makanan pedas mempercepat kelahiran. Mitos ini tidak terbukti secara ilmiah. Yang terpenting adalah menjaga pola makan seimbang dan memenuhi kebutuhan gizi agar ibu dan bayi sehat selama melahirkan.'),
      _Blok(_pen, 'Persalinan harus dilakukan di fasilitas kesehatan agar masalah bisa segera ditangani.'),
    ],
  ),
  _Bab(
    'Tanda Bahaya pada Kehamilan',
    'Kapan ibu hamil harus segera ke Puskesmas atau rumah sakit',
    Icons.warning_amber_rounded,
    [
      _Blok(_pen,
          'Jika mengalami tanda bahaya pada masa kehamilan, segera bawa ibu hamil periksa ke Puskesmas atau rumah sakit.'),
      _Blok(_sub, 'Trimester 1'),
      _Blok(_pnt, 'Demam tinggi.'),
      _Blok(_pnt, 'Nyeri perut hebat.'),
      _Blok(_pnt, 'Mual dan muntah hebat.'),
      _Blok(_pnt, 'Perdarahan.'),
      _Blok(_pnt, 'Sakit saat kencing, keputihan, atau gatal di daerah kemaluan.'),
      _Blok(_pnt, 'Demam, menggigil, dan berkeringat (di daerah endemis malaria, bisa menandakan malaria).'),
      _Blok(_pnt, 'Diare berulang.'),
      _Blok(_pnt, 'Batuk lama (lebih dari 2 minggu).'),
      _Blok(_pnt, 'Jantung berdebar-debar atau nyeri di dada.'),
      _Blok(_pnt, 'Sulit tidur dan cemas berlebihan.'),
      _Blok(_sub, 'Trimester 2'),
      _Blok(_pnt, 'Demam tinggi, muntah darah, dan nyeri perut hebat.'),
      _Blok(_pnt, 'Napas pendek dan jantung berdebar kencang.'),
      _Blok(_pnt, 'Pandangan kabur, pusing atau sakit kepala berat.'),
      _Blok(_pnt, 'Perdarahan atau keluar cairan dari jalan lahir yang sangat banyak atau berbau.'),
      _Blok(_pnt, 'Sakit saat kencing, keputihan, atau gatal di daerah kemaluan.'),
      _Blok(_sub, 'Trimester 3'),
      _Blok(_pnt, 'Gerakan bayi tidak ada atau kurang dari 10 kali dalam 12 jam.'),
      _Blok(_pnt, 'Ketuban pecah namun tidak ada kontraksi.'),
      _Blok(_pnt, 'Nyeri perut hebat di antara kontraksi.'),
      _Blok(_pnt, 'Perdarahan hebat.'),
      _Blok(_pnt, 'Pusing atau sakit kepala berat.'),
      _Blok(_sub, 'Pantau sendiri setiap minggu'),
      _Blok(_pnt, 'Demam lebih dari 2 hari dan pusing atau sakit kepala berat.'),
      _Blok(_pnt, 'Batuk lebih dari 2 minggu atau kontak serumah dengan penderita TB.'),
      _Blok(_pnt, 'Gerakan bayi tidak ada atau kurang dari 10 kali dalam 12 jam setelah minggu ke-24.'),
      _Blok(_pnt, 'Keluar cairan dari jalan lahir yang sangat banyak atau berbau.'),
    ],
  ),
  _Bab(
    'Perawatan Sehari-hari Ibu Hamil',
    'Kebiasaan baik dan hal yang perlu dihindari',
    Icons.self_improvement,
    [
      _Blok(_sub, 'Perawatan sehari-hari'),
      _Blok(_pnt, 'Jaga kebersihan diri: cuci tangan pakai sabun dan air mengalir, mandi, dan ganti pakaian teratur.'),
      _Blok(_pnt, 'Istirahat cukup: tidur malam paling sedikit 6-7 jam dan tidur siang 1-2 jam.'),
      _Blok(_pnt, 'Rangsang pertumbuhan bayi dengan sering berbicara dan menyentuh perut ibu.'),
      _Blok(_pnt, 'Hubungan suami istri selama hamil boleh dilakukan selama kondisi kehamilan sehat.'),
      _Blok(_sub, 'Hal yang tidak boleh dilakukan'),
      _Blok(_pnt, 'Minum obat tanpa resep dokter dan jamu.'),
      _Blok(_pnt, 'Minum minuman beralkohol.'),
      _Blok(_pnt, 'Merokok atau terpapar asap rokok.'),
      _Blok(_pnt, 'Aktivitas berat yang membuat ibu kelelahan.'),
      _Blok(_pnt, 'Stres berlebihan.'),
      _Blok(_sub, 'Aktivitas fisik yang tidak boleh dilakukan'),
      _Blok(_pnt, 'Jongkok terlalu lama dan membungkuk tanpa pegangan.'),
      _Blok(_pnt, 'Melompat dan mengejan.'),
      _Blok(_pnt, 'Tidur telentang lebih dari 10 menit pada trimester 2 dan 3, untuk menghindari kekurangan oksigen pada bayi.'),
      _Blok(_pen, 'Risiko keseimbangan meningkat selama hamil, jadi berhati-hatilah saat bergerak.'),
    ],
  ),
  _Bab(
    'Porsi Makan Ibu Hamil dan Menyusui',
    'Kebutuhan gizi harian dalam porsi',
    Icons.restaurant_outlined,
    [
      _Blok(_par, 'Porsi disesuaikan dengan bahan makanan lokal. Tenaga kesehatan akan membantu menjelaskannya.'),
      _Blok(_sub, 'Ibu hamil trimester 1 (12 minggu pertama)'),
      _Blok(_pnt, 'Nasi atau makanan pokok: 5 porsi.'),
      _Blok(_pnt, 'Protein hewani (ikan, telur, ayam): 4 porsi.'),
      _Blok(_pnt, 'Protein nabati (tempe, tahu): 4 porsi.'),
      _Blok(_pnt, 'Sayuran: 4 porsi. Buah: 4 porsi.'),
      _Blok(_pnt, 'Minyak/lemak: 5 porsi. Gula: 2 porsi.'),
      _Blok(_sub, 'Ibu hamil trimester 2 dan 3 (minggu ke-12 sampai 40)'),
      _Blok(_pnt, 'Nasi atau makanan pokok: 6 porsi.'),
      _Blok(_pnt, 'Protein hewani: 4 porsi. Protein nabati: 4 porsi.'),
      _Blok(_pnt, 'Sayuran: 4 porsi. Buah: 4 porsi.'),
      _Blok(_pnt, 'Minyak/lemak: 5 porsi. Gula: 2 porsi.'),
      _Blok(_sub, 'Ibu menyusui 0-12 bulan'),
      _Blok(_pnt, 'Nasi atau makanan pokok: 6 porsi.'),
      _Blok(_pnt, 'Protein hewani: 4 porsi. Protein nabati: 4 porsi.'),
      _Blok(_pnt, 'Sayuran: 4 porsi. Buah: 4 porsi.'),
      _Blok(_pnt, 'Minyak/lemak: 6 porsi. Gula: 2 porsi.'),
      _Blok(_pnt, 'Air putih: 14 gelas per hari pada 6 bulan pertama dan 12 gelas per hari pada 6 bulan kedua.'),
      _Blok(_sub, 'Ukuran satu porsi'),
      _Blok(_pnt, 'Makanan pokok: 100 g atau 3/4 gelas nasi, atau 125 g (3 buah jagung sedang), atau 210 g (2 kentang sedang), atau 70 g (3 iris roti putih), atau 200 g (2 gelas mi basah).'),
      _Blok(_pnt, 'Protein hewani: 50 g (1 potong sedang ikan) atau 55 g (1 butir telur ayam).'),
      _Blok(_pnt, 'Protein nabati: 50 g (1 potong sedang tempe) atau 100 g (2 potong sedang tahu).'),
      _Blok(_pnt, 'Sayuran: 100 g atau 1 mangkuk sayur matang tanpa kuah.'),
      _Blok(_pnt, 'Buah: 100 g (1 potong sedang pisang) atau 100-190 g (1 potong besar pepaya).'),
      _Blok(_pnt, 'Minyak/lemak: 5 g atau 1 sendok teh, termasuk dari menggoreng, menumis, dan santan.'),
      _Blok(_pnt, 'Gula: 10 g atau 1 sendok makan.'),
      _Blok(_pen, 'Batasi garam paling banyak 1 sendok teh per hari dan minum air putih 8-12 gelas per hari saat hamil.'),
    ],
  ),
  _Bab(
    'Kesehatan Jiwa dan Kelas Ibu Hamil',
    'Menjaga emosi ibu selama kehamilan',
    Icons.psychology_outlined,
    [
      _Blok(_par,
          'Selama kehamilan ibu dapat mengalami gejolak emosi seperti mudah sedih, mudah marah, stres, cemas, dan depresi. Hal ini memengaruhi kesehatan ibu dan perkembangan bayi.'),
      _Blok(_sub, 'Kenali gejalanya'),
      _Blok(_pnt, 'Kecemasan dan rasa khawatir yang berlebihan.'),
      _Blok(_pnt, 'Gelisah, gemetar, tidak bisa rileks, otot tegang, dan sakit kepala.'),
      _Blok(_pnt, 'Berdebar, berkeringat, sesak napas, kepala terasa ringan, dan tidak nyaman di ulu hati.'),
      _Blok(_pnt, 'Lelah berkepanjangan tetapi sulit tidur.'),
      _Blok(_pnt, 'Mudah tersinggung dan marah.'),
      _Blok(_pnt, 'Perubahan hubungan dengan suami.'),
      _Blok(_sub, 'Yang harus dilakukan'),
      _Blok(_pnt, 'Tidur cukup dan makan makanan bergizi.'),
      _Blok(_pnt, 'Periksa masalah kesehatan jiwa ke Puskesmas atau fasilitas kesehatan.'),
      _Blok(_pnt, 'Suami dan keluarga mendampingi serta memberi perhatian dan bantuan.'),
      _Blok(_sub, 'Ikuti kelas ibu hamil'),
      _Blok(_pnt, 'Mempersiapkan tubuh dan mental untuk kelancaran melahirkan.'),
      _Blok(_pnt, 'Mendapat dukungan dari ibu-ibu lain dan informasi tentang kehamilan, persalinan, nifas, perawatan bayi, gizi, dan pelayanan kesehatan.'),
      _Blok(_pnt, 'Tanyakan jadwal dan tempat kelas kepada petugas kesehatan. Suami diminta ikut paling sedikit 1 kali.'),
      _Blok(_pen, 'Kesehatan jiwa yang baik selama kehamilan adalah kunci persalinan yang sehat dan awal yang baik bagi ibu dan bayi.'),
    ],
  ),
  _Bab(
    'Melahirkan dan Inisiasi Menyusu Dini',
    'Tanda awal, tanda bahaya, dan IMD',
    Icons.local_hospital_outlined,
    [
      _Blok(_par,
          'Persalinan harus dilakukan di Puskesmas, rumah sakit, atau klinik bersalin agar masalah dapat segera ditangani. Ibu idealnya melahirkan pada usia kehamilan 38-40 minggu.'),
      _Blok(_sub, 'Tanda awal melahirkan'),
      _Blok(_pnt, 'Keluar lendir bercampur darah atau cairan ketuban dari jalan lahir.'),
      _Blok(_pnt, 'Perut mulas teratur, makin sering dan makin lama.'),
      _Blok(_sub, 'Tanda bahaya saat melahirkan (segera rujuk ke rumah sakit)'),
      _Blok(_pnt, 'Air ketuban hijau dan berbau.'),
      _Blok(_pnt, 'Ibu gelisah atau kesakitan hebat, atau kejang.'),
      _Blok(_pnt, 'Ibu tidak kuat mengejan.'),
      _Blok(_pnt, 'Perdarahan lewat jalan lahir.'),
      _Blok(_pnt, 'Tali pusat atau tangan bayi keluar dari jalan lahir.'),
      _Blok(_sub, 'Yang perlu diketahui'),
      _Blok(_pnt, 'Pada kehamilan pertama, bayi biasanya lahir sekitar 12 jam sejak mulas. Pada kehamilan berikutnya biasanya lebih cepat.'),
      _Blok(_pnt, 'Ibu berhak memilih didampingi atau tidak, siapa pendampingnya, dan posisi melahirkan (diskusikan posisi yang aman).'),
      _Blok(_pnt, 'Jika ingin buang air besar, segera beritahu petugas.'),
      _Blok(_pnt, 'Untuk mengurangi nyeri, tarik napas lewat hidung dan keluarkan lewat mulut.'),
      _Blok(_pnt, 'Ibu dan bayi dirawat dalam satu ruangan dan paling sedikit 24 jam setelah melahirkan normal.'),
      _Blok(_sub, 'Inisiasi Menyusu Dini (IMD)'),
      _Blok(_par,
          'Bayi segera ditempelkan kulit ke kulit dengan ibu setelah lahir selama paling sedikit 1 jam. Setelah menyusu di jam pertama, bayi biasanya tidur panjang dan menyusu lagi bila lapar.'),
      _Blok(_pnt, 'Menenangkan ibu dan bayi serta menjaga kehangatan bayi.'),
      _Blok(_pnt, 'Kolostrum mengandung gizi dan antibodi yang meningkatkan daya tahan tubuh bayi.'),
      _Blok(_pnt, 'Meningkatkan kesehatan pencernaan dan mengurangi risiko diare.'),
      _Blok(_pnt, 'Menstimulasi produksi ASI dan memperpanjang durasi menyusui.'),
      _Blok(_pnt, 'Mengurangi perdarahan karena gerakan bayi merangsang kontraksi rahim.'),
      _Blok(_pnt, 'Mempercepat pelepasan plasenta.'),
      _Blok(_pen, 'Kontak kulit ke kulit juga membangun ikatan kasih sayang (bonding) antara ibu dan bayi.'),
    ],
  ),
  _Bab(
    'Setelah Melahirkan (Nifas)',
    'Pemulihan ibu sampai 42 hari',
    Icons.favorite_border,
    [
      _Blok(_par,
          'Kematian ibu tertinggi terjadi pada masa setelah melahirkan. Ibu mengalami banyak perubahan fisik, hormonal, dan emosional. Kolostrum (ASI pertama) keluar sekitar 5-10 ml pada hari pertama.'),
      _Blok(_sub, 'Periksa paling sedikit 4 kali'),
      _Blok(_pnt, 'Pertama: 6 jam sampai 2 hari setelah melahirkan.'),
      _Blok(_pnt, 'Kedua: 3-7 hari setelah melahirkan.'),
      _Blok(_pnt, 'Ketiga: 8-28 hari setelah melahirkan.'),
      _Blok(_pnt, 'Keempat (ibu saja): 29-42 hari setelah melahirkan.'),
      _Blok(_sub, 'Yang harus dilakukan'),
      _Blok(_pnt, 'Konsumsi tablet tambah darah untuk mencegah anemia.'),
      _Blok(_pnt, 'Makan lebih banyak dan lebih sering: 3 kali makanan utama dan 1-2 kali kudapan, beragam, dan cukup minum.'),
      _Blok(_pnt, 'Temui tenaga kesehatan atau konselor menyusui bila ada masalah menyusui.'),
      _Blok(_pnt, 'Periksa jika setelah 2 minggu atau lebih ibu masih mudah murung, sedih, atau depresi.'),
      _Blok(_pnt, 'Ayah dan keluarga berbagi peran mengasuh, membantu merawat bayi dan menyusui.'),
      _Blok(_sub, 'Tanda bahaya pada ibu nifas'),
      _Blok(_pnt, 'Demam lebih dari 2 hari.'),
      _Blok(_pnt, 'Perdarahan lewat jalan lahir.'),
      _Blok(_pnt, 'Keluar cairan berbau dari jalan lahir.'),
      _Blok(_pnt, 'Payudara bengkak, merah, disertai rasa sakit.'),
      _Blok(_pnt, 'Nyeri ulu hati, mual muntah, sakit kepala, pandangan kabur, atau kejang dengan atau tanpa bengkak pada kaki, tangan, dan wajah.'),
      _Blok(_pnt, 'Ibu tampak sedih, murung, dan menangis tanpa sebab.'),
      _Blok(_sub, 'Yang tidak boleh dilakukan'),
      _Blok(_pnt, 'Membersihkan payudara dengan alkohol, povidon iodine, obat merah, atau sabun karena bisa terminum bayi.'),
      _Blok(_pnt, 'Membuang ASI pertama (kolostrum) karena sangat berguna bagi kekebalan bayi.'),
      _Blok(_pnt, 'Latihan fisik posisi telungkup dan mengikat perut terlalu kencang.'),
      _Blok(_pnt, 'Menempelkan daun-daunan pada kemaluan karena menimbulkan infeksi.'),
      _Blok(_pen, 'Segera ke Puskesmas atau rumah sakit jika mengalami tanda bahaya masa nifas.'),
    ],
  ),
  _Bab(
    'Depresi Setelah Melahirkan',
    'Mengenali baby blues dan depresi pasca melahirkan',
    Icons.mood_bad_outlined,
    [
      _Blok(_sub, 'Baby blues'),
      _Blok(_par,
          'Terjadi setelah melahirkan dan memuncak dalam beberapa hari hingga 2 minggu. Gejala: perasaan tidak stabil, mudah menangis, sulit tidur, mudah cemas, dan mudah tersinggung.'),
      _Blok(_sub, 'Depresi setelah melahirkan'),
      _Blok(_pnt, 'Dapat terjadi dalam 2 minggu setelah melahirkan, paling cepat 48-72 jam pertama. Gejala: mudah tersinggung, perubahan perasaan dan perilaku, gangguan tidur, halusinasi, dan waham.'),
      _Blok(_pnt, 'Dapat terjadi sekitar 4 minggu setelah melahirkan, paling sedikit 2 minggu berturut-turut. Gejala: sangat sedih, sulit konsentrasi, gangguan tidur, tidak selera makan atau banyak makan, mudah marah, lelah, tidak bergairah, rasa bersalah, khawatir tidak bisa menjadi ibu yang baik, dan pikiran untuk melukai diri atau bayinya.'),
      _Blok(_sub, 'Pencegahan'),
      _Blok(_pnt, 'Ibu dan keluarga mengenali tanda-tanda masalah kesehatan jiwa.'),
      _Blok(_pnt, 'Kontrol teratur ke bidan atau dokter saat hamil.'),
      _Blok(_pnt, 'Makan makanan sehat dan bergizi termasuk vitamin.'),
      _Blok(_pnt, 'Deteksi dini faktor risiko pada ibu hamil dan setelah melahirkan.'),
      _Blok(_pnt, 'Dukungan dan perhatian dari suami, keluarga, dan teman.'),
      _Blok(_sub, 'Penanganan'),
      _Blok(_pnt, 'Dukungan keluarga, terutama suami, agar tidak hanya bayi yang diperhatikan.'),
      _Blok(_pnt, 'Ada yang membantu mengasuh bayi dan mengajak ibu bicara tentang perasaannya.'),
      _Blok(_pnt, 'Kunjungan rumah oleh tenaga kesehatan, konseling, dan terapi obat bila diperlukan.'),
      _Blok(_pen, 'Segera cari bantuan tenaga kesehatan jika ibu mengalami pikiran untuk melukai diri atau bayinya.'),
    ],
  ),
  _Bab(
    'Keluarga Berencana (KB)',
    'Mengatur jarak dan jumlah anak',
    Icons.family_restroom,
    [
      _Blok(_par,
          'Kehamilan yang sehat adalah kehamilan yang direncanakan, diinginkan, dan dijaga perkembangannya. Syaratnya kesehatan fisik dan mental layak untuk hamil, usia 20-35 tahun, jarak kehamilan 2 tahun, dan jumlah anak kurang dari 3.'),
      _Blok(_par,
          'KB pascasalin dapat dimulai langsung sesudah melahirkan sampai 42 hari. Pilih metode yang tidak mengganggu produksi ASI dan sesuai kondisi ibu.'),
      _Blok(_sub, 'Mengapa perlu ber-KB'),
      _Blok(_pnt, 'Mengatur jarak kehamilan, paling sedikit 2 tahun setelah melahirkan.'),
      _Blok(_pnt, 'Mengatur jumlah anak, sebaiknya tidak lebih dari tiga.'),
      _Blok(_pnt, 'Mencegah kehamilan yang tidak diinginkan.'),
      _Blok(_pnt, 'Menjaga kesehatan ibu, bayi, dan balita.'),
      _Blok(_pnt, 'Ibu punya waktu dan perhatian cukup untuk diri sendiri, anak, dan keluarga.'),
      _Blok(_sub, 'Metode jangka panjang'),
      _Blok(_pnt, 'MOW dan MOP (metode operasi wanita dan pria).'),
      _Blok(_pnt, 'AKDR atau spiral, dapat dipakai sampai 10 tahun.'),
      _Blok(_pnt, 'Implan (di bawah kulit), dipakai selama 3 tahun.'),
      _Blok(_sub, 'Metode bukan jangka panjang'),
      _Blok(_pnt, 'Pil KB dan kondom.'),
      _Blok(_pnt, 'Suntik 3 bulan, diberikan setelah 6 minggu pascasalin.'),
      _Blok(_pen, 'Ibu menyusui tidak disarankan memakai KB suntik 1 bulan karena dapat mengganggu produksi ASI.'),
    ],
  ),
  _Bab(
    'Menyusui yang Benar',
    'Manfaat, posisi, dan pelekatan',
    Icons.volunteer_activism_outlined,
    [
      _Blok(_par,
          'ASI mengandung semua gizi yang dibutuhkan bayi dan menjaga daya tahan tubuhnya. Berikan hanya ASI sampai usia 6 bulan, lalu lanjutkan sampai usia 2 tahun.'),
      _Blok(_sub, 'Manfaat menyusui bagi ibu'),
      _Blok(_pnt, 'Mencegah kanker payudara.'),
      _Blok(_pnt, 'Mempercepat kembali ke berat badan semula.'),
      _Blok(_pnt, 'Menjadi metode KB alami.'),
      _Blok(_pnt, 'Mempercepat rahim kembali ke ukuran semula dan mencegah perdarahan setelah melahirkan.'),
      _Blok(_pnt, 'Memperkuat ikatan dengan bayi serta menjaga kesehatan mental ibu.'),
      _Blok(_sub, 'Cara menyusui'),
      _Blok(_pnt, 'Susui sesering mungkin atau semau bayi (8-12 kali sehari atau lebih).'),
      _Blok(_pnt, 'Jika bayi tidur lebih dari 3 jam, bangunkan lalu susui.'),
      _Blok(_pnt, 'Susui sampai payudara terasa kosong, lalu pindah ke sisi lain.'),
      _Blok(_pnt, 'Jika bayi kenyang tetapi payudara masih penuh, perah dan simpan ASI untuk mencegah mastitis dan menjaga pasokan ASI.'),
      _Blok(_sub, 'Posisi yang benar'),
      _Blok(_pnt, 'Kepala dan badan bayi membentuk garis lurus.'),
      _Blok(_pnt, 'Wajah bayi menghadap payudara, hidung berhadapan dengan puting.'),
      _Blok(_pnt, 'Badan bayi dekat dengan tubuh ibu dan didekap utuh.'),
      _Blok(_sub, 'Pelekatan yang benar'),
      _Blok(_pnt, 'Mulut bayi terbuka lebar dan dekat dengan payudara.'),
      _Blok(_pnt, 'Dagu bayi menyentuh payudara.'),
      _Blok(_pnt, 'Areola bagian atas lebih banyak terlihat daripada bagian bawah mulut bayi.'),
      _Blok(_pnt, 'Bibir bawah bayi memutar keluar.'),
      _Blok(_pen, 'Konseling menyusui tersedia gratis di Puskesmas.'),
    ],
  ),
  _Bab(
    'Memerah dan Menyimpan ASI',
    'Cara memerah, menyimpan, dan memberikan ASI perah',
    Icons.local_drink_outlined,
    [
      _Blok(_sub, 'Persiapan wadah'),
      _Blok(_pnt, 'Cuci cangkir atau gelas kecil dengan sabun, lalu tuang air mendidih dan diamkan beberapa menit. Buang airnya saat akan dipakai.'),
      _Blok(_pnt, 'Untuk kolostrum di hari-hari pertama, gunakan sendok sebagai wadah.'),
      _Blok(_sub, 'Cara memerah'),
      _Blok(_pnt, 'Letakkan ibu jari di atas puting dan areola, jari telunjuk dan tengah di bawahnya, di seberang ibu jari.'),
      _Blok(_pnt, 'Tekan payudara di belakang puting dan areola, lalu lepaskan, sampai ASI menetes.'),
      _Blok(_pnt, 'Perah satu payudara 3-5 menit, pindah ke sisi lain, lalu ulangi. Total sekitar 20-30 menit.'),
      _Blok(_sub, 'Lama penyimpanan ASI'),
      _Blok(_pnt, 'Suhu ruang 27-32 derajat C: 4 jam. Di bawah 25 derajat C: 6-8 jam.'),
      _Blok(_pnt, 'Cooler bag dengan es: 24 jam.'),
      _Blok(_pnt, 'Kulkas (di bawah 4 derajat C): 48-72 jam.'),
      _Blok(_pnt, 'Freezer lemari es 1 pintu: 2 minggu. Freezer 2 pintu: 3-6 bulan.'),
      _Blok(_sub, 'Tips penyimpanan dan pemberian'),
      _Blok(_pnt, 'Simpan ASI 15-60 ml per wadah dan beri label tanggal.'),
      _Blok(_pnt, 'Cairkan ASI beku perlahan di kulkas atau dalam wadah berisi air hangat, dan gunakan dalam 24 jam.'),
      _Blok(_pnt, 'ASI yang sudah hangat sebaiknya dipakai dalam waktu satu jam.'),
      _Blok(_pnt, 'Jangan merebus ASI atau memanaskannya di microwave.'),
      _Blok(_pnt, 'Beri ASI dengan cangkir: bungkus bayi, gendong setengah tegak, letakkan cangkir di bibir bawah bayi. Jangan menuang ASI ke mulut bayi karena dapat masuk ke saluran napas.'),
      _Blok(_pen, 'Hindari ASI perah mengalami perubahan suhu yang terlalu ekstrem.'),
    ],
  ),

  // ========================= PERJALANAN ANAK =========================
  _Bab(
    'Bayi Baru Lahir (0-28 Hari)',
    'Perawatan dan pemeriksaan bayi di bulan pertama',
    Icons.baby_changing_station,
    [
      _Blok(_par,
          'Satu bulan pertama adalah masa penting bagi kelangsungan hidup bayi. Dua pertiga kematian balita di Indonesia terjadi pada 28 hari pertama. Bayi tidur sampai 16 jam sehari.'),
      _Blok(_sub, 'Pemeriksaan oleh tenaga kesehatan'),
      _Blok(_pnt, '0-6 jam, 6-48 jam, 3-7 hari, dan 8-28 hari setelah lahir.'),
      _Blok(_pnt, 'Imunisasi hepatitis B (HB0) sebelum 24 jam.'),
      _Blok(_pnt, 'Skrining hipotiroid kongenital (SHK) 48-72 jam setelah lahir.'),
      _Blok(_pnt, 'Skrining penyakit jantung bawaan (PJB) kritis 24-48 jam setelah lahir.'),
      _Blok(_sub, 'Menjaga bayi tetap hangat'),
      _Blok(_pnt, 'Mandikan dengan air hangat 6 jam setelah lahir, bila kondisi stabil.'),
      _Blok(_pnt, 'Sebelum tali pusat lepas, mandikan dengan dilap. Setelah lepas, bayi boleh dimasukkan ke air, hati-hati agar kepala tidak terendam.'),
      _Blok(_pnt, 'Bersihkan kemaluan dari depan ke belakang.'),
      _Blok(_pnt, 'Beri pakaian dan selimut, topi, kaus kaki, dan kaus tangan bila dingin. Segera ganti baju dan popok yang basah.'),
      _Blok(_pnt, 'Jika memakai kipas angin, jangan langsung mengenai bayi. Suhu AC sekitar 25-26 derajat C.'),
      _Blok(_sub, 'Merawat tali pusat'),
      _Blok(_pnt, 'Cuci tangan dengan sabun sebelum dan sesudah memegang bayi.'),
      _Blok(_pnt, 'Jangan memberikan apa pun pada tali pusat.'),
      _Blok(_pnt, 'Rawat tali pusat terbuka dan kering. Jika kotor atau basah, cuci dengan air bersih dan sabun, lalu keringkan.'),
      _Blok(_sub, 'Tidur yang aman'),
      _Blok(_pnt, 'Tidurkan bayi telentang di alas yang rata.'),
      _Blok(_pnt, 'Jauhkan benda yang dapat menutupi kepala.'),
      _Blok(_pnt, 'Gunakan kelambu.'),
      _Blok(_sub, 'Bayi kecil dan perawatan metode kanguru'),
      _Blok(_pnt, 'Bayi berat lahir kurang dari 2500 gram atau usia kehamilan 37 minggu atau kurang menggunakan Buku KIA Khusus Bayi Kecil.'),
      _Blok(_pnt, 'Perawatan metode kanguru (kontak kulit ke kulit saat tidur dan istirahat) menjaga kehangatan dan meningkatkan asupan ASI. Ayah dapat bergantian melakukannya.'),
      _Blok(_sub, 'Warna tinja'),
      _Blok(_pnt, 'Periksa warna tinja bayi setiap hari sampai usia 4 bulan.'),
      _Blok(_pnt, 'Jika tinja pucat (mendekati nomor 1 sampai 3 pada kartu warna), segera bawa ke dokter karena mungkin ada sumbatan kandung empedu (atresia bilier).'),
      _Blok(_pnt, 'Jika mata masih kuning atau urin kuning keruh setelah usia 2 minggu, segera bawa ke dokter.'),
      _Blok(_pen, 'Sunat pada bayi perempuan tidak bermanfaat bagi kesehatan dan berisiko tinggi.'),
    ],
  ),
  _Bab(
    'Tanda Bahaya Bayi 0-28 Hari',
    'Segera periksa ke bidan, dokter, atau perawat',
    Icons.warning_amber_rounded,
    [
      _Blok(_pen, 'Jika bayi mengalami salah satu tanda berikut, segera periksa ke bidan, dokter, atau perawat.'),
      _Blok(_sub, 'Tanda bahaya'),
      _Blok(_pnt, 'Demam tinggi atau tubuh dingin.'),
      _Blok(_pnt, 'Kejang (mata mendelik, tangan menari, mulut mencucu, tangisan melengking).'),
      _Blok(_pnt, 'Sesak napas, napas cepat, atau dada tertarik ke dalam. Napas normal 40-60 kali per menit.'),
      _Blok(_pnt, 'Tidak mau menyusu atau hisapan lemah.'),
      _Blok(_pnt, 'Muntah susu atau cairan hijau.'),
      _Blok(_pnt, 'Kencing kurang dari 6 kali per hari atau warna kencing kurang pekat.'),
      _Blok(_pnt, 'Lemah, tidak bergerak, atau menangis dan merintih terus-menerus.'),
      _Blok(_pnt, 'Kulit dan mata kuning.'),
      _Blok(_pnt, 'Warna kulit biru atau memar di sekitar mulut, tangan, atau kaki.'),
      _Blok(_pnt, 'Tali pusat kemerahan sampai dinding perut, berbau, atau bernanah.'),
      _Blok(_pnt, 'Diare dan tinja bayi berwarna pucat.'),
      _Blok(_pen, 'Cek kondisi bayi setiap hari selama 28 hari pertama.'),
    ],
  ),
  _Bab(
    'ASI Eksklusif 0-6 Bulan',
    'Hanya ASI sampai bayi berusia 6 bulan',
    Icons.child_care,
    [
      _Blok(_par,
          'Pada masa ini bayi tumbuh pesat, ditandai penambahan berat dan panjang badan yang cepat.'),
      _Blok(_sub, 'Yang harus dilakukan'),
      _Blok(_pnt, 'Beri hanya ASI sampai usia 6 bulan.'),
      _Blok(_pnt, 'Jangan tambahkan air putih, makanan, minuman, obat, vitamin, atau mineral kecuali dianjurkan dokter atau tenaga kesehatan.'),
      _Blok(_pnt, 'Susui semau bayi dan hindari botol susu atau dot.'),
      _Blok(_pnt, 'Temui tenaga kesehatan atau konselor menyusui bila ada masalah menyusui.'),
      _Blok(_pnt, 'Timbang, ukur panjang badan, dan cek perkembangan bayi tiap bulan di Posyandu.'),
      _Blok(_pnt, 'Dapatkan imunisasi dasar lengkap sesuai usia.'),
      _Blok(_pnt, 'Sering ajak bayi berkomunikasi dan bermain, dan pastikan bayi cukup istirahat.'),
      _Blok(_sub, 'Mengapa harus dilakukan'),
      _Blok(_pnt, 'Meningkatkan ikatan ibu dan bayi.'),
      _Blok(_pnt, 'Bayi mendapat gizi cukup dan terhindar dari masalah gizi seperti stunting.'),
      _Blok(_pnt, 'Mendukung perkembangan otak dan kemampuan belajar.'),
      _Blok(_pnt, 'Imunisasi dasar melindungi bayi dari penyakit yang dapat menyebabkan kematian.'),
      _Blok(_sub, 'Perilaku menyusu bayi baru lahir'),
      _Blok(_pnt, 'Hari pertama: lambung sebesar kelereng, menyusu 5-12 kali dalam 24 jam.'),
      _Blok(_pnt, 'Hari ke-2 sampai ke-3: lambung sebesar bola pingpong, menyusu 10-12 kali.'),
      _Blok(_pnt, 'Satu minggu: lambung sebesar telur ayam, menyusu rata-rata 8 kali.'),
      _Blok(_pnt, 'Satu bulan: lambung sebesar telur bebek, menyusu 8-12 kali.'),
      _Blok(_pen, 'Tanda bayi lapar: lebih banyak bergerak, memutar kepala, mengisap jari, dan mengecap mulut. Ibu sebaiknya selalu dekat dengan bayi.'),
    ],
  ),
  _Bab(
    'Tumbuh Kembang Bayi 0-6 Bulan',
    'Stimulasi, penanda perkembangan, dan perawatan',
    Icons.toys_outlined,
    [
      _Blok(_sub, 'Stimulasi usia 29 hari - 3 bulan'),
      _Blok(_pnt, 'Peluk, cium, ayun bayi.'),
      _Blok(_pnt, 'Senyum, tatap mata, ajak bicara.'),
      _Blok(_pnt, 'Tirukan ocehan dan mimik bayi.'),
      _Blok(_pnt, 'Kenalkan berbagai suara, bunyi, dan nyanyian.'),
      _Blok(_pnt, 'Gantung benda berwarna dan berbunyi.'),
      _Blok(_pnt, 'Gulingkan kanan-kiri, tengkurap-telentang.'),
      _Blok(_sub, 'Penanda perkembangan 29 hari - 3 bulan'),
      _Blok(_pnt, 'Mengangkat kepala hingga 45 derajat, menggerakkan kepala dari kiri atau kanan ke tengah.'),
      _Blok(_pnt, 'Menatap wajah ibu, mengoceh, tertawa keras, terkejut mendengar suara keras.'),
      _Blok(_pnt, 'Membalas senyum dan mengenal ibu lewat penglihatan, penciuman, pendengaran, dan kontak.'),
      _Blok(_sub, 'Stimulasi usia 3-6 bulan'),
      _Blok(_pnt, 'Peluk, cium, pandang mata, senyum, bicara.'),
      _Blok(_pnt, 'Mencari sumber suara, bermain cilukba, melihat wajah di cermin.'),
      _Blok(_pnt, 'Meraih dan mengamati benda kecil atau bergerak.'),
      _Blok(_pnt, 'Berguling dan belajar duduk.'),
      _Blok(_sub, 'Penanda perkembangan 3-6 bulan'),
      _Blok(_pnt, 'Berbalik dari telungkup ke telentang.'),
      _Blok(_pnt, 'Mengangkat kepala tegak 90 derajat dan mempertahankannya stabil.'),
      _Blok(_pnt, 'Menggenggam mainan, meraih benda, dan mengamati tangannya sendiri.'),
      _Blok(_pnt, 'Mengeluarkan suara gembira bernada tinggi dan tersenyum melihat mainan menarik.'),
      _Blok(_sub, 'Perawatan gigi bayi'),
      _Blok(_pnt, 'Gendong atau pangku bayi dengan satu tangan.'),
      _Blok(_pnt, 'Bersihkan gusi perlahan dengan kain atau lap basah yang dililitkan pada jari telunjuk.'),
      _Blok(_sub, 'Pola asuh sampai usia 18 bulan'),
      _Blok(_pnt, 'Tangisan menandakan bayi butuh bantuan. Jangan biarkan menangis lama karena membuatnya stres.'),
      _Blok(_pnt, 'Bayi usia 4-12 bulan perlu tidur 12-16 jam sehari (termasuk tidur siang).'),
      _Blok(_pnt, 'Anak di bawah 18 bulan tidak menggunakan gawai kecuali video call dengan didampingi orang tua.'),
      _Blok(_pen, 'Jika bayi belum bisa melakukan salah satu penanda perkembangan sesuai usianya, segera bawa ke Puskesmas.'),
    ],
  ),
  _Bab(
    'MP-ASI 6-12 Bulan',
    'Makanan pendamping ASI yang kaya protein hewani',
    Icons.rice_bowl_outlined,
    [
      _Blok(_par,
          'Di usia 6-12 bulan bayi berkembang pesat dan membutuhkan gizi lengkap, terutama protein hewani, untuk mencegah stunting dan infeksi.'),
      _Blok(_sub, 'Yang akan dialami'),
      _Blok(_pnt, 'Pengalaman makan pertama dan beradaptasi dengan berbagai tekstur.'),
      _Blok(_pnt, 'Mulai tumbuh gigi, kadang disertai diare dan demam.'),
      _Blok(_pnt, 'Mulai berbalik, tengkurap, dan merangkak di usia 8-9 bulan.'),
      _Blok(_sub, 'Yang harus dilakukan'),
      _Blok(_pnt, 'Berikan MP-ASI kaya protein hewani.'),
      _Blok(_pnt, 'Latih bayi menyenangi suasana makan dan peka terhadap responsnya.'),
      _Blok(_pnt, 'Lanjutkan ASI hingga usia 2 tahun atau lebih.'),
      _Blok(_pnt, 'Cek perkembangan tiap bulan di Posyandu.'),
      _Blok(_pnt, 'Pastikan bayi mendapat vitamin A kapsul biru 1 kali setahun.'),
      _Blok(_pnt, 'Dapatkan Pemeriksaan Kesehatan Anak Terintegrasi (PKAT) di usia 6-7 bulan.'),
      _Blok(_pnt, 'Ajari bayi makan dengan sendok dan minum dengan gelas.'),
      _Blok(_sub, 'Kelompok makanan MP-ASI'),
      _Blok(_pnt, 'ASI, makanan pokok, kacang-kacangan, susu hewani dan turunannya, daging-dagingan, telur, buah dan sayuran kaya vitamin A, serta buah dan sayuran lainnya.'),
      _Blok(_sub, 'Tips'),
      _Blok(_pnt, 'Kenalkan makanan satu per satu sambil memperhatikan kemungkinan alergi.'),
      _Blok(_pnt, 'Masak dengan direbus atau dikukus. Hindari gorengan, pengawet, serta gula dan garam tinggi.'),
      _Blok(_pnt, 'Mulai dari tekstur lunak dan lembut (bubur pisang apel pir, bubur sup daging kacang merah, puding kentang ayam telur).'),
      _Blok(_pnt, 'Usia 9-11 bulan lanjut ke tekstur lebih kasar tapi tetap lembut (sup daging cincang, nasi tim ikan kembung telur puyuh).'),
      _Blok(_pen, 'Segera ke fasilitas kesehatan bila bayi sakit atau mengalami tanda bahaya.'),
    ],
  ),
  _Bab(
    'Pemenuhan Gizi 6-24 Bulan',
    'Syarat, tekstur, porsi, dan contoh MP-ASI',
    Icons.soup_kitchen_outlined,
    [
      _Blok(_par, 'Lanjutkan pemberian ASI disertai MP-ASI. MP-ASI yang baik harus memenuhi syarat berikut.'),
      _Blok(_sub, 'Empat syarat MP-ASI'),
      _Blok(_pnt, 'Tepat waktu: mulai usia 6 bulan, saat ASI saja tidak lagi cukup.'),
      _Blok(_pnt, 'Cukup: jumlah, frekuensi, tekstur, dan variasi sesuai kebutuhan. Prioritaskan protein hewani (ikan, ayam, daging, hati, udang, telur, susu) dan mulai kenalkan protein nabati (kedelai, kacang hijau, kacang tanah). Lemak dari minyak atau santan. Kenalkan buah dan sayur kaya vitamin A dan C.'),
      _Blok(_pnt, 'Aman: jaga kebersihan makanan dan alat, cuci tangan sebelum menyiapkan dan memberi makan.'),
      _Blok(_pnt, 'Cara yang benar: teratur (pagi, siang, sore), maksimal 30 menit, suasana netral tanpa bermain atau menonton TV, ajari anak makan sendiri.'),
      _Blok(_sub, 'Bayi 6-8 bulan'),
      _Blok(_pnt, 'Tekstur lumat dan kental (disaring). Cairan 800 ml per hari.'),
      _Blok(_pnt, 'Mulai 2-3 sendok makan bertahap sampai 1/2 mangkuk 250 ml (125 ml) setiap makan.'),
      _Blok(_pnt, '2-3 kali makanan utama dan 1-2 kali selingan. Energi dari MP-ASI sekitar 200 kkal per hari.'),
      _Blok(_sub, 'Bayi 9-11 bulan'),
      _Blok(_pnt, 'Tekstur dicincang. Perhatikan respons anak saat makan.'),
      _Blok(_pnt, '1/2 sampai 3/4 mangkuk 250 ml (125-200 ml) setiap makan.'),
      _Blok(_pnt, '3-4 kali makanan utama dan 1-2 kali selingan. Energi sekitar 300 kkal per hari.'),
      _Blok(_sub, 'Anak 12-23 bulan'),
      _Blok(_pnt, 'Makanan keluarga yang diiris-iris. Cairan 1.300 ml per hari.'),
      _Blok(_pnt, '3/4 sampai 1 mangkuk 250 ml setiap makan.'),
      _Blok(_pnt, '3-4 kali makanan utama dan 1-2 kali selingan. Energi sekitar 550 kkal per hari. ASI dilanjutkan sampai 2 tahun atau lebih.'),
      _Blok(_sub, 'Contoh menu'),
      _Blok(_pnt, '6-8 bulan: nasi putih 30 g, dadar telur 35 g, sayur kare wortel tempe 20 g, dilumatkan dan disaring dengan kuah sampai seperti bubur kental.'),
      _Blok(_pnt, '9-11 bulan: nasi putih 45 g, ikan kembung bumbu kuning 30 g, tumis buncis 25 g, dicincang.'),
      _Blok(_pnt, '12-23 bulan: nasi putih 55 g, semur hati ayam 45 g, bening bayam 20 g, sebagai makanan keluarga.'),
      _Blok(_pnt, 'Contoh selingan: perkedel kentang isi daging.'),
      _Blok(_sub, 'Resep singkat'),
      _Blok(_pnt, 'Bubur sup daging kacang merah (6-8 bulan): kaldu ayam, kacang merah, daging ayam cincang, nasi, buncis, wortel, telur, dihaluskan sesuai tekstur.'),
      _Blok(_pnt, 'Nasi tim ikan kembung telur puyuh (9-12 bulan): nasi, ikan kembung, telur puyuh, wortel, tomat, minyak kelapa, dan kaldu, ditim sampai matang dan disajikan dengan saus pepaya.'),
      _Blok(_pen, 'Cari resep MP-ASI lainnya melalui kode QR di Buku KIA atau tanyakan kepada kader.'),
    ],
  ),
  _Bab(
    'Tumbuh Kembang Bayi 6-12 Bulan',
    'Stimulasi, perawatan gigi, dan penanda perkembangan',
    Icons.sentiment_satisfied_alt_outlined,
    [
      _Blok(_sub, 'Layanan bulanan di Posyandu'),
      _Blok(_pnt, 'Pemantauan pertumbuhan dan perkembangan.'),
      _Blok(_pnt, 'Kelas ibu balita untuk ibu, ayah, dan keluarga.'),
      _Blok(_pnt, 'Kapsul vitamin A (Februari atau Agustus) dan imunisasi.'),
      _Blok(_sub, 'Stimulasi usia 6-9 bulan'),
      _Blok(_pnt, 'Peluk, senyum, bicara, panggil namanya, bersalaman, tepuk tangan, melambai.'),
      _Blok(_pnt, 'Kenalkan nama orang dan benda, bermain cilukba, melihat cermin, bacakan dongeng.'),
      _Blok(_pnt, 'Pegang mainan dengan 2 tangan, masukkan benda kecil ke wadah, sembunyikan dan cari mainan.'),
      _Blok(_pnt, 'Duduk, merangkak, berdiri berpegangan.'),
      _Blok(_sub, 'Penanda perkembangan 6-9 bulan'),
      _Blok(_pnt, 'Duduk mandiri, belajar berdiri, merangkak meraih mainan.'),
      _Blok(_pnt, 'Memindahkan benda dari satu tangan ke tangan lain, memungut 2 benda sekaligus.'),
      _Blok(_pnt, 'Bersuara tanpa arti (mamama, bababa), mencari benda yang dijatuhkan.'),
      _Blok(_pnt, 'Bermain cilukba, mengenal anggota keluarga dan takut pada orang asing.'),
      _Blok(_sub, 'Stimulasi usia 9-12 bulan'),
      _Blok(_pnt, 'Berbicara dengan boneka, menunjuk dan menyebut orang, benda, atau anggota tubuh.'),
      _Blok(_pnt, 'Menyusun balok, memegang pensil dan mencoret-coret.'),
      _Blok(_pnt, 'Berjalan mundur dan berjinjit.'),
      _Blok(_sub, 'Penanda perkembangan 9-12 bulan'),
      _Blok(_pnt, 'Mengangkat badan ke posisi berdiri, berdiri 30 detik atau berpegangan, berjalan dituntun.'),
      _Blok(_pnt, 'Menggenggam erat pensil, menirukan bunyi, menyebut 2-3 suku kata yang sama.'),
      _Blok(_sub, 'Perawatan gigi'),
      _Blok(_pnt, 'Perhatikan tumbuhnya gigi seri atas dan bawah. Pada usia 9 bulan ada 8 gigi seri dan 4 geraham.'),
      _Blok(_pnt, 'Bersihkan gigi dengan kasa dan air hangat, atau sikat bayi berbulu halus dengan pasta gigi selapis tipis.'),
      _Blok(_pen, 'Jika bayi belum bisa melakukan salah satu penanda perkembangan, segera bawa ke Puskesmas.'),
    ],
  ),
  _Bab(
    'Anak 12-24 Bulan',
    'Cegah stunting dengan gizi dan pemantauan rutin',
    Icons.directions_walk,
    [
      _Blok(_par,
          'Stunting paling banyak terjadi pada kelompok usia ini. Anak sudah makan makanan keluarga, mulai berjalan dan berkata-kata. Sekitar 70 persen kebutuhan gizi dipenuhi dari MP-ASI dan 30 persen dari ASI.'),
      _Blok(_sub, 'Yang harus dilakukan'),
      _Blok(_pnt, 'Timbang, ukur, dan cek perkembangan anak setiap bulan.'),
      _Blok(_pnt, 'Beri MP-ASI kaya protein hewani seperti telur, ikan, dan daging, beragam dan menarik.'),
      _Blok(_pnt, 'Tetap beri ASI sampai usia 2 tahun.'),
      _Blok(_pnt, 'Ajari anak makan sendiri, berjalan di undakan, mencoret-coret, dan menyebut bagian tubuh.'),
      _Blok(_pnt, 'Ajak anak membereskan mainan, bernyanyi, dan bermain dengan teman. Bacakan cerita.'),
      _Blok(_pnt, 'Dapatkan imunisasi lanjutan, vitamin A kapsul merah, dan obat cacing 2 kali setahun.'),
      _Blok(_sub, 'Hindari'),
      _Blok(_pnt, 'Jajanan rendah gizi, tinggi gula dan garam, berpengawet, dan berpemanis.'),
      _Blok(_pnt, 'Susu atau yoghurt rendah lemak, minuman bersoda, minuman kemasan dan kalengan.'),
      _Blok(_pnt, 'Makanan terlalu asam dan pedas, serta makanan instan yang banyak MSG dan pengawet.'),
      _Blok(_sub, 'Frekuensi makan'),
      _Blok(_pnt, '3-4 kali makanan utama dan 1-2 kali selingan. Anak mulai memilih-milih makanan.'),
      _Blok(_sub, 'Stimulasi 12-18 bulan'),
      _Blok(_pnt, 'Berjalan mundur, naik tangga, menangkap dan melempar bola.'),
      _Blok(_pnt, 'Menyusun balok atau puzzle, menggambar, bermain air, meniup, menendang bola.'),
      _Blok(_pnt, 'Bercerita tentang gambar, menyebut nama benda, bermain dengan teman sebaya, merapikan mainan.'),
      _Blok(_sub, 'Stimulasi 18-24 bulan'),
      _Blok(_pnt, 'Bicara, bertanya, bercerita, bernyanyi, dan tanya jawab.'),
      _Blok(_pnt, 'Perintah sederhana, melepas baju, makan dengan sendok garpu.'),
      _Blok(_pnt, 'Berjalan, berlari, melompat, berdiri satu kaki, melempar dan menendang bola.'),
      _Blok(_sub, 'Penanda perkembangan'),
      _Blok(_pnt, '12-18 bulan: berdiri sendiri 30 detik, berjalan tanpa terhuyung, memungut benda kecil, menumpuk 2 kubus, menyebut 3-6 kata bermakna, makan minum sendiri.'),
      _Blok(_pnt, '18-24 bulan: membungkuk memungut mainan lalu berdiri, berjalan mundur 5 langkah, menumpuk 4 kubus, membantu pekerjaan rumah.'),
      _Blok(_sub, 'Perawatan gigi'),
      _Blok(_pnt, 'Usia 18 bulan gigi susu berjumlah 16, usia 24 bulan berjumlah 20.'),
      _Blok(_pnt, 'Sikat gigi setelah sarapan dan sebelum tidur dengan sikat lembut khusus anak dan pasta gigi berfluor selapis tipis (setengah biji kacang polong).'),
      _Blok(_pen, 'Jika anak belum bisa melakukan salah satu penanda perkembangan, segera bawa ke Puskesmas.'),
    ],
  ),
  _Bab(
    'Anak 2-6 Tahun',
    'Gizi, cairan, dan tumbuh kembang anak prasekolah',
    Icons.school_outlined,
    [
      _Blok(_par,
          'Di usia 2 tahun ke atas perkembangan fisik, mental, dan sosial anak berkembang pesat hingga usia 6 tahun. Anak mulai disapih, lebih aktif, bergaul lebih luas, dan memasuki masa prasekolah. Otak berkembang sangat pesat pada 3 tahun pertama.'),
      _Blok(_sub, 'Yang harus dilakukan'),
      _Blok(_pnt, 'Beri makanan keluarga bervariasi dan kaya protein hewani.'),
      _Blok(_pnt, 'Timbang, ukur, dan cek perkembangan anak setiap bulan di Posyandu, fasilitas kesehatan, atau PAUD.'),
      _Blok(_pnt, 'Libatkan anak dalam kegiatan bersama, kembangkan kreativitas dan kemampuan bergaul.'),
      _Blok(_pnt, 'Ajarkan perbedaan jenis kelamin dan cara menjaga alat kelamin.'),
      _Blok(_pnt, 'Pastikan anak mendapat vitamin A kapsul merah dan obat cacing 2 kali setahun.'),
      _Blok(_sub, 'Gizi anak 2-5 tahun'),
      _Blok(_pnt, 'Biasakan makan 3 kali sehari bersama keluarga.'),
      _Blok(_pnt, 'Penuhi protein seperti ikan, telur, tempe, susu, dan tahu, serta sayur dan buah.'),
      _Blok(_pnt, 'Batasi selingan yang terlalu manis, asin, dan berlemak.'),
      _Blok(_pnt, 'Biasakan bermain dan aktivitas fisik setiap hari.'),
      _Blok(_sub, 'Kebutuhan cairan'),
      _Blok(_pnt, 'Usia 2-3 tahun sekitar 1.300 ml per hari (sekitar 5 gelas belimbing).'),
      _Blok(_pnt, 'Usia di atas 3 tahun sekitar 1.700 ml per hari (sekitar 7 gelas belimbing).'),
      _Blok(_sub, 'Warna air kencing'),
      _Blok(_pnt, 'Baik: anak terhidrasi baik, teruskan minum air putih.'),
      _Blok(_pnt, 'Kurang baik: kurang terhidrasi, tambahkan minum.'),
      _Blok(_pnt, 'Tidak baik: sangat kurang minum, segera beri minum. Jika warna tidak membaik, hubungi bidan, perawat, atau dokter.'),
      _Blok(_sub, 'Penanda perkembangan 2-3 tahun'),
      _Blok(_pnt, 'Naik tangga sendiri, menendang bola kecil, mencoret-coret, bicara dengan 2 kata.'),
      _Blok(_pnt, 'Menunjuk bagian tubuh, menyebut nama 2 benda atau lebih pada gambar.'),
      _Blok(_pnt, 'Makan nasi sendiri tanpa banyak tumpah, melepas pakaian sendiri.'),
      _Blok(_sub, 'Penanda perkembangan 3-4 tahun'),
      _Blok(_pnt, 'Berdiri 1 kaki 2 detik, melompat dua kaki, mengayuh sepeda roda tiga.'),
      _Blok(_pnt, 'Menggambar garis lurus, menumpuk 8 kubus, mengenal 2-4 warna.'),
      _Blok(_pnt, 'Menyebut nama, umur, tempat, memahami kata di atas, di bawah, di depan.'),
      _Blok(_pnt, 'Mencuci dan mengeringkan tangan sendiri, bermain bersama teman, memakai sepatu dan baju sendiri.'),
      _Blok(_sub, 'Penanda perkembangan 4-5 tahun'),
      _Blok(_pnt, 'Berdiri 1 kaki 6 detik, melompat-lompat 1 kaki, menari.'),
      _Blok(_pnt, 'Menggambar tanda silang, lingkaran, dan orang dengan 3 bagian tubuh.'),
      _Blok(_pnt, 'Mengancingkan baju, menyebut nama lengkap, menjawab pertanyaan dengan kata yang benar, bicara mudah dimengerti.'),
      _Blok(_pnt, 'Membandingkan ukuran dan bentuk, menyebut angka dan menghitung jari.'),
      _Blok(_sub, 'Penanda perkembangan 5-6 tahun'),
      _Blok(_pnt, 'Berjalan lurus, berdiri 1 kaki 11 detik, menangkap bola kecil dengan dua tangan.'),
      _Blok(_pnt, 'Menggambar orang lengkap dan segi empat.'),
      _Blok(_pnt, 'Mengerti lawan kata, pembicaraan 7 kata atau lebih, dan menjawab tentang benda terbuat dari apa dan kegunaannya.'),
      _Blok(_sub, 'Stimulasi 4-6 tahun'),
      _Blok(_pnt, 'Bermain peran, bercerita pengalaman, mengenal huruf dan angka, nama hari, jam, dan tanggal.'),
      _Blok(_pnt, 'Main bola, lompat tali, menggunting, menempel, menggambar, mewarnai, menulis nama.'),
      _Blok(_pnt, 'Melatih mengikuti aturan permainan, memakai pakaian sendiri, dan menguatkan kepercayaan diri anak.'),
      _Blok(_pen, 'Jika anak belum bisa melakukan salah satu penanda perkembangan sesuai usianya, segera bawa ke Puskesmas.'),
    ],
  ),
  _Bab(
    'Pola Asuh, Tidur, dan Gawai',
    'Mengasuh anak 1,5-6 tahun dengan penuh kasih sayang',
    Icons.bedtime_outlined,
    [
      _Blok(_sub, 'Pola asuh anak 1,5-3 tahun'),
      _Blok(_pnt, 'Hargai dan akui kemampuan anak.'),
      _Blok(_pnt, 'Dorong anak bergerak bebas, hindari larangan yang tidak perlu, tetapi lindungi dari bahaya.'),
      _Blok(_pnt, 'Ajak bermain dan berbicara dengan kalimat pendek yang bermakna.'),
      _Blok(_pnt, 'Dorong anak bermain dengan anak lain, latih sopan santun dan disiplin sederhana.'),
      _Blok(_pnt, 'Anak 1-2 tahun perlu tidur 11-14 jam sehari (termasuk tidur siang).'),
      _Blok(_sub, 'Pola asuh anak 3-6 tahun'),
      _Blok(_pnt, 'Ayah, ibu, dan keluarga bekerja sama. Anak mencontoh peran orang tua sesama jenis.'),
      _Blok(_pnt, 'Ajari konsep perbedaan laki-laki dan perempuan.'),
      _Blok(_pnt, 'Ajari anak menjaga bagian pribadinya (alat kelamin, paha, dada, pantat, dan kaki) untuk menghindari pelecehan.'),
      _Blok(_pnt, 'Bantu anak mengucapkan kata dengan benar dan beri kepercayaan melakukan hal tertentu secara mandiri.'),
      _Blok(_pnt, 'Saat anak ketakutan, dekap dia, bicarakan ketakutannya, dan buat ia merasa dimengerti.'),
      _Blok(_pnt, 'Anak 3-5 tahun perlu tidur 10-13 jam sehari (termasuk tidur siang).'),
      _Blok(_sub, 'Penggunaan gawai'),
      _Blok(_pnt, 'Usia 18-24 bulan: pilih konten berkualitas, tidak lebih dari 1 jam per hari, dan selalu didampingi orang tua.'),
      _Blok(_pnt, 'Usia di atas 24 bulan: batasi tidak lebih dari 1 jam per hari dan pilih konten berkualitas.'),
      _Blok(_pnt, 'Jangan memakai gawai saat makan dan 1 jam sebelum tidur.'),
      _Blok(_pnt, 'Matikan TV dan perangkat media bila tidak digunakan.'),
      _Blok(_pnt, 'Jangan memakai gawai untuk menenangkan perilaku anak. Siapkan aktivitas alternatif.'),
      _Blok(_pnt, 'Usahakan kamar tidur, waktu makan, dan waktu bermain bebas dari gawai.'),
      _Blok(_pen, 'Penggunaan gawai berlebih berdampak pada keterlambatan bicara, kurang interaksi, tantrum, dan gangguan kognitif.'),
    ],
  ),
  _Bab(
    'Imunisasi dan Suplemen',
    'Jadwal imunisasi dasar bayi dan baduta serta manfaatnya',
    Icons.vaccines_outlined,
    [
      _Blok(_par,
          'Imunisasi melindungi anak dari penyakit berbahaya. Jadwal pasti ditentukan bidan atau petugas kesehatan. Lengkapi imunisasi dasar sesuai usia.'),
      _Blok(_sub, 'Jadwal imunisasi dasar'),
      _Blok(_pnt, '0-24 jam: Hepatitis B (HB0).'),
      _Blok(_pnt, '1 bulan: BCG dan Polio tetes 1.'),
      _Blok(_pnt, '2 bulan: DPT-HB-Hib 1, Polio tetes 2, PCV 1, dan Rotavirus (RV) 1.'),
      _Blok(_pnt, '3 bulan: DPT-HB-Hib 2, Polio tetes 3, PCV 2, dan RV 2.'),
      _Blok(_pnt, '4 bulan: DPT-HB-Hib 3, Polio tetes 4, Polio suntik (IPV) 1, dan RV 3.'),
      _Blok(_pnt, '9 bulan: Campak-Rubella (MR) dan Polio suntik (IPV) 2.'),
      _Blok(_pnt, '10 bulan: Japanese Encephalitis (JE), hanya di daerah endemis.'),
      _Blok(_pnt, '12 bulan: PCV 3.'),
      _Blok(_pnt, '18 bulan: DPT-HB-Hib lanjutan dan Campak-Rubella lanjutan.'),
      _Blok(_sub, 'Manfaat imunisasi'),
      _Blok(_pnt, 'BCG: mencegah TBC.'),
      _Blok(_pnt, 'Polio: mencegah polio yang menyebabkan lumpuh layu.'),
      _Blok(_pnt, 'DPT-HB-Hib: mencegah difteri, pertusis (batuk rejan), tetanus, hepatitis B, serta pneumonia dan meningitis akibat bakteri Hib.'),
      _Blok(_pnt, 'PCV: mencegah pneumonia akibat bakteri pneumokokus.'),
      _Blok(_pnt, 'Rotavirus: mencegah diare berat yang menyebabkan dehidrasi dan kematian.'),
      _Blok(_pnt, 'Campak-Rubella: mencegah radang paru, radang otak, dan kebutaan.'),
      _Blok(_pnt, 'JE: mencegah radang otak.'),
      _Blok(_pnt, 'Imunisasi lanjutan: mengulang imunisasi dasar untuk mempertahankan kekebalan dan memperpanjang perlindungan.'),
      _Blok(_sub, 'Suplemen'),
      _Blok(_pnt, 'Vitamin A diberikan pada bulan Februari dan Agustus. Bayi 6-11 bulan mendapat kapsul biru, anak 12 bulan ke atas kapsul merah.'),
      _Blok(_pnt, 'Vitamin A meningkatkan kesehatan mata dan pertumbuhan anak.'),
      _Blok(_pnt, 'Obat cacing mencegah dan mengobati cacingan.'),
      _Blok(_pen, 'Bila ada imunisasi yang terlewat, tetap bawa anak ke Posyandu atau Puskesmas. Imunisasi dapat dilanjutkan sesuai saran bidan.'),
    ],
  ),
  _Bab(
    'Tanda Bahaya pada Balita',
    'Anak usia 29 hari sampai 5 tahun yang harus segera ke fasilitas kesehatan',
    Icons.warning_amber_rounded,
    [
      _Blok(_pen, 'Jika anak mengalami salah satu tanda berikut, segera periksa ke bidan, dokter, perawat, atau Puskesmas.'),
      _Blok(_sub, 'Tanda bahaya'),
      _Blok(_pnt, 'Demam atau panas tinggi (suhu lebih dari 38,5 derajat C).'),
      _Blok(_pnt, 'Kejang.'),
      _Blok(_pnt, 'Sesak napas, cuping hidung kembang kempis, atau dada tertarik ke dalam. Batuk berbunyi grok-grok atau mengi.'),
      _Blok(_pnt, 'Tampak biru (sianosis) di sekitar mulut, tangan, atau kaki.'),
      _Blok(_pnt, 'Muntah-muntah, tidak bisa minum, atau tidak mau makan dan minum.'),
      _Blok(_pnt, 'Diare: BAB lebih sering dan lebih encer, mata cekung, haus minum dengan lahap, atau disertai darah.'),
      _Blok(_pnt, 'Jumlah air kencing sedikit atau tidak kencing selama 6 jam, warna kuning pekat atau kecoklatan.'),
      _Blok(_pnt, 'Tanda perdarahan: mimisan, gusi berdarah, muntah seperti kopi, atau BAB hitam.'),
      _Blok(_pnt, 'Pembengkakan yang nyeri di belakang telinga.'),
      _Blok(_pnt, 'Lemah, tidak bergerak, atau menangis dan merintih.'),
      _Blok(_pnt, 'Berat badan tidak naik sesuai pertumbuhan.'),
      _Blok(_pen, 'Bawa anak setiap bulan ke Posyandu atau Puskesmas untuk pemantauan tumbuh kembang, imunisasi, vitamin A, dan obat cacing.'),
    ],
  ),
  _Bab(
    'Merawat Anak Sakit',
    'Demam, batuk, diare, dan luka di rumah',
    Icons.healing_outlined,
    [
      _Blok(_par,
          'Saat sakit daya tahan tubuh anak melemah sehingga ia butuh lebih banyak zat gizi. Tetap tenang dan pastikan kebutuhan gizinya tercukupi.'),
      _Blok(_sub, 'Gizi saat anak sakit'),
      _Blok(_pnt, 'Beri asupan lebih banyak: tambah porsi ASI, makanan, minuman, atau variasi makanan.'),
      _Blok(_pnt, 'Beri makan lebih sering, misalnya tambah 1-2 kali dari biasanya dengan porsi yang tidak membuat anak terlalu kenyang.'),
      _Blok(_sub, 'Demam'),
      _Blok(_pnt, 'Beri ASI lebih sering dan beri minum lebih sering dan lebih banyak.'),
      _Blok(_pnt, 'Jangan diselimuti atau diberi baju tebal.'),
      _Blok(_pnt, 'Kompres dengan air biasa atau air hangat. Jangan dengan air dingin karena anak bisa menggigil.'),
      _Blok(_pnt, 'Jika demam tinggi, beri obat penurun panas sesuai dosis.'),
      _Blok(_pnt, 'Di daerah endemis malaria, balita tidur dalam kelambu berinsektisida.'),
      _Blok(_pnt, 'Segera ke fasilitas kesehatan jika demam disertai kejang, tidak turun dalam 2 hari setelah obat penurun panas, atau disertai bintik merah, perdarahan di hidung, atau BAB hitam.'),
      _Blok(_sub, 'Batuk'),
      _Blok(_pnt, 'Beri ASI lebih sering dan air matang lebih banyak.'),
      _Blok(_pnt, 'Anak di atas 1 tahun boleh diberi kecap manis atau madu dicampur air jeruk nipis sebagai pelega tenggorokan.'),
      _Blok(_pnt, 'Jauhkan dari asap rokok, asap dapur, asap sampah, polusi kendaraan, dan debu.'),
      _Blok(_pnt, 'Segera ke fasilitas kesehatan jika batuk tidak sembuh dalam 2 hari, anak sesak napas, atau demam.'),
      _Blok(_sub, 'Diare atau mencret'),
      _Blok(_pnt, 'Jika masih menyusu, beri ASI sesering mungkin, lebih sering dan lebih lama dari biasanya.'),
      _Blok(_pnt, 'Beri 1/2 sampai 1 gelas oralit setiap anak BAB. Jika tidak ada, beri air matang, kuah sayur bening, atau air tajin.'),
      _Blok(_pnt, 'Beri zinc sekali sehari selama 10 hari berturut-turut: 1/2 tablet untuk usia di bawah 6 bulan, 1 tablet untuk usia 6 bulan sampai 5 tahun.'),
      _Blok(_pnt, 'Beri MP-ASI atau makan seperti biasa. Jangan beri obat apa pun kecuali dari petugas kesehatan.'),
      _Blok(_pnt, 'Segera ke fasilitas kesehatan jika timbul demam, ada darah dalam tinja, diare makin parah, muntah terus-menerus, anak sangat haus, tidak mau makan dan minum, atau diare berulang.'),
      _Blok(_sub, 'Luka dan koreng'),
      _Blok(_pnt, 'Luka: cuci bersih dengan air mengalir. Koreng: periksakan ke Puskesmas.'),
      _Blok(_pnt, 'Segera ke fasilitas kesehatan jika luka bernanah atau berbau.'),
      _Blok(_pen, 'Pencegahan diare: gizi seimbang, kebersihan makanan, cukup cairan (anak 2-6 tahun minimal 5-7 gelas air per hari), dan cuci tangan.'),
    ],
  ),
  _Bab(
    'Perawatan Gigi Anak',
    'Cara membersihkan gigi dan mencegah gigi berlubang',
    Icons.sentiment_very_satisfied_outlined,
    [
      _Blok(_sub, 'Cara membersihkan gigi sesuai usia'),
      _Blok(_pnt, '0-4 bulan: bersihkan gusi perlahan dengan kain atau lap basah yang dililitkan pada jari telunjuk.'),
      _Blok(_pnt, '6-12 bulan: bersihkan gusi setelah makan. Jika gigi susu muncul, pakai sikat bayi berbulu halus tanpa pasta atau dengan pasta selapis tipis.'),
      _Blok(_pnt, '2-6 tahun: pasta gigi seukuran biji kacang polong. Menyikat gigi 2 menit di depan cermin, teratur, dan didampingi sampai usia 8 tahun.'),
      _Blok(_sub, 'Jadwal tumbuh gigi'),
      _Blok(_pnt, 'Usia 9 bulan: 8 gigi seri dan 4 geraham.'),
      _Blok(_pnt, 'Usia 18 bulan: 16 gigi susu. Usia 24 bulan: 20 gigi susu.'),
      _Blok(_pnt, 'Usia 5-6 tahun: mulai tumbuh 2 geraham tetap rahang bawah. Periksakan gigi tiap 3-6 bulan ke dokter gigi atau perawat gigi.'),
      _Blok(_sub, 'Faktor risiko gigi berlubang'),
      _Blok(_pnt, 'Minum susu botol saat tidur malam.'),
      _Blok(_pnt, 'Mengemil makanan manis di antara waktu makan, terutama yang lengket.'),
      _Blok(_pnt, 'Tidak menyikat gigi sebelum tidur.'),
      _Blok(_pnt, 'Mengemut makanan, menghisap ibu jari, atau mengempeng.'),
      _Blok(_pen, 'Sikat gigi setelah sarapan dan sebelum tidur setiap hari.'),
    ],
  ),
  _Bab(
    'Cuci Tangan dan Kebersihan Lingkungan',
    'PHBS, air minum, makanan, dan sanitasi rumah',
    Icons.clean_hands_outlined,
    [
      _Blok(_sub, 'Kapan harus mencuci tangan'),
      _Blok(_pnt, 'Setelah buang air dan setelah menceboki bayi atau anak.'),
      _Blok(_pnt, 'Sebelum memegang dan menyusui bayi.'),
      _Blok(_pnt, 'Sebelum makan, menyuapi anak, dan memegang makanan, serta setelah makan.'),
      _Blok(_pnt, 'Setelah bersin atau batuk.'),
      _Blok(_pnt, 'Setiap kali tangan kotor: mengetik, memegang uang, hewan, atau berkebun.'),
      _Blok(_sub, 'Mengapa harus pakai sabun'),
      _Blok(_pnt, 'Kuman mudah menular lewat tangan dan masuk ke tubuh saat makan.'),
      _Blok(_pnt, 'Tangan yang tampak bersih tetap bisa mengandung kuman.'),
      _Blok(_pnt, 'Sabun membersihkan kotoran dan merontokkan kuman.'),
      _Blok(_sub, 'Cara cuci tangan yang benar'),
      _Blok(_pnt, 'Basahi tangan dengan air bersih mengalir, gosok sabun merata.'),
      _Blok(_pnt, 'Gosok telapak, punggung tangan, sela-sela jari, dan bagian bawah kuku.'),
      _Blok(_pnt, 'Bilas dengan air mengalir, lalu keringkan dengan handuk atau tisu bersih atau diangin-anginkan.'),
      _Blok(_sub, 'Kesehatan lingkungan rumah'),
      _Blok(_pnt, 'Buang air besar di jamban sehat dengan kloset leher angsa dan tangki septik yang disedot teratur. Jangan buang air sembarangan.'),
      _Blok(_pnt, 'Sediakan sarana cuci tangan: tempat, air mengalir, dan sabun.'),
      _Blok(_pnt, 'Olah air minum dengan direbus. Jika keruh, endapkan atau saring. Simpan dalam wadah tertutup rapat dan ambil dengan cara aman.'),
      _Blok(_pnt, 'Tutup makanan dengan penutup bersih dan jauhkan dari bahan berbahaya seperti deterjen, pestisida, dan obat nyamuk.'),
      _Blok(_pnt, 'Pisahkan makanan mentah dan matang, masak sampai matang, dan jangan biarkan makanan matang di luar lebih dari 4 jam.'),
      _Blok(_pnt, 'Kelola sampah: tempat sampah tertutup, pilah sampah, jangan dibakar, dan jangan dibuang ke sungai, kebun, atau saluran air.'),
      _Blok(_pnt, 'Jauhkan anak dari asap rokok.'),
      _Blok(_pen, 'Kebersihan yang baik membantu gizi anak terserap dengan baik dan mencegah diare.'),
    ],
  ),
  _Bab(
    'Perlindungan Anak dari Kekerasan',
    'Melindungi anak dari kekerasan fisik, psikis, dan seksual',
    Icons.shield_outlined,
    [
      _Blok(_par,
          'Lindungi anak dari kekerasan fisik, psikis, seksual, dan penelantaran. Banyak pelaku adalah orang yang dikenal anak.'),
      _Blok(_sub, 'Contoh bentuk kekerasan'),
      _Blok(_pnt, 'Kekerasan fisik: mencubit, memukul.'),
      _Blok(_pnt, 'Kekerasan psikis: mengejek, mengancam.'),
      _Blok(_pnt, 'Kekerasan seksual: perbuatan cabul terhadap anak atau mempertontonkan aktivitas seksual kepada anak.'),
      _Blok(_pnt, 'Penelantaran: tidak memenuhi kebutuhan gizi, kesehatan, dan pendidikan.'),
      _Blok(_sub, 'Bangun komunikasi dengan anak'),
      _Blok(_pnt, 'Dengarkan cerita anak dengan penuh perhatian.'),
      _Blok(_pnt, 'Belajar melihat dari sudut pandang anak. Jangan cepat mengkritik atau mencela.'),
      _Blok(_pnt, 'Hargai pendapat dan seleranya.'),
      _Blok(_pnt, 'Jika anak bercerita tentang hal berbahaya, tanyakan bagaimana mereka menghindarinya.'),
      _Blok(_sub, 'Ajarkan anak'),
      _Blok(_pnt, 'Tidak boleh ada orang yang menyentuh bagian pribadinya: kelamin, paha, dada, pantat, dan kaki.'),
      _Blok(_sub, 'Yang perlu dilakukan orang tua'),
      _Blok(_pnt, 'Kenali dan penuhi hak anak.'),
      _Blok(_pnt, 'Kelola stres Anda dan anggota keluarga lainnya.'),
      _Blok(_pnt, 'Ketahui selalu keberadaan anak dan pastikan pengasuh dapat dipercaya.'),
      _Blok(_sub, 'Tanda-tanda kekerasan pada anak'),
      _Blok(_pnt, 'Memar dan luka yang tidak bisa dijelaskan.'),
      _Blok(_pnt, 'Gangguan makan dan tidur.'),
      _Blok(_pnt, 'Perubahan perilaku.'),
      _Blok(_pnt, 'Infeksi menular seksual.'),
    ],
  ),
  _Bab(
    'Keselamatan Anak di Rumah',
    'Mencegah jatuh, luka bakar, tersedak, dan tenggelam',
    Icons.health_and_safety_outlined,
    [
      _Blok(_sub, 'Hindarkan anak dari risiko jatuh'),
      _Blok(_pnt, 'Ikat atau tempelkan TV, meja, lemari, dan rak yang tidak kuat ke dinding. Beri bantalan pada sudut tajam.'),
      _Blok(_pnt, 'Baby walker tidak disarankan karena menghambat langkah anak dan dapat membuat bayi terjatuh.'),
      _Blok(_pnt, 'Jendela paling sedikit 1 meter dari lantai. Periksa gerbang pagar rumah.'),
      _Blok(_pnt, 'Jangan tinggalkan bayi sendirian di tempat tinggi.'),
      _Blok(_pnt, 'Pasang pagar pada tangga dan balkon dengan jarak antarpagar tidak lebih dari 9 cm.'),
      _Blok(_pnt, 'Pasang pengaman di sekitar tempat tidur anak.'),
      _Blok(_sub, 'Hindarkan dari luka bakar dan bahaya listrik'),
      _Blok(_pnt, 'Jauhkan anak dari kabel listrik dan panci panas.'),
      _Blok(_pnt, 'Pasang soket listrik jauh dari jangkauan anak atau gunakan penutup.'),
      _Blok(_pnt, 'Jangan memegang barang panas saat memegang atau memangku bayi.'),
      _Blok(_sub, 'Mencegah bayi kekurangan napas'),
      _Blok(_pnt, 'Jangan beri makanan keras yang sulit dikunyah.'),
      _Blok(_pnt, 'Jauhkan benda yang berisiko menjerat atau menyumbat: tali panjang, kantong plastik, mainan kecil.'),
      _Blok(_pnt, 'Hindari menidurkan bayi telungkup tanpa pengawasan.'),
      _Blok(_sub, 'Hindarkan dari bahaya tenggelam'),
      _Blok(_pnt, 'Jangan biarkan anak sendiri di bak mandi atau ember, atau bermain di tepi kolam tanpa pengawasan.'),
      _Blok(_pnt, 'Beri pembatas aman agar anak tidak leluasa menjangkau sumber air.'),
      _Blok(_pnt, 'Usia 1 tahun 6 bulan diajari tentang bahaya air. Usia 2 tahun diajari melayang saat jatuh ke air dan berenang jarak pendek. Usia 6 tahun sebaiknya bisa berenang dengan keterampilan bertahan di air.'),
    ],
  ),
  _Bab(
    'Kesiapsiagaan Bencana',
    'Persiapan keluarga dengan ibu hamil, bayi, dan balita',
    Icons.backpack_outlined,
    [
      _Blok(_par,
          'Indonesia rawan bencana. Kelompok paling rentan adalah ibu hamil, ibu nifas, bayi, dan balita. Pengungsian yang padat dengan sanitasi buruk berisiko menimbulkan penyakit menular, gizi kurang, pelecehan, kekerasan, trauma, dan anak terpisah dari orang tua.'),
      _Blok(_par,
          'Reaksi anak 1-2 tahun dipengaruhi suasana jiwa orang tua. Jika orang tua panik, anak jadi gelisah, rewel, dan mudah sakit. Anak prasekolah mudah merasa tidak berdaya dan sulit tidur. Bimbingan bermain dapat membantu.'),
      _Blok(_sub, 'Kesiapsiagaan'),
      _Blok(_pnt, 'Buat rencana darurat keluarga dan kenali ancaman bencana.'),
      _Blok(_pnt, 'Catat nomor kontak penting: keluarga, Puskesmas, rumah sakit, klinik, dan bidan.'),
      _Blok(_pnt, 'Ketahui lokasi mematikan air, gas, dan listrik.'),
      _Blok(_pnt, 'Tentukan titik kumpul dan titik aman di rumah.'),
      _Blok(_sub, 'Isi tas kit bencana'),
      _Blok(_pnt, 'Buku KIA, obat rutin, vitamin, dan perlengkapan pendukung.'),
      _Blok(_pnt, 'Kalung tanda pengenal berisi nama, nama orang tua, nomor telepon, dan alamat.'),
      _Blok(_pnt, 'Perlengkapan bayi dan balita: pakaian, selimut, popok, topi, kaus kaki, mainan.'),
      _Blok(_pnt, 'Perlengkapan ibu: kain panjang dan pakaian.'),
      _Blok(_pnt, 'Makanan instan, air mineral, roti, dan makanan praktis.'),
      _Blok(_pnt, 'Tisu basah dan kering, hand sanitizer, perlengkapan mandi.'),
      _Blok(_pnt, 'Ponsel, powerbank, charger, radio, dan baterai.'),
      _Blok(_pnt, 'Senter, peluit, pisau serbaguna, dan korek.'),
      _Blok(_pnt, 'Uang tunai, KTP, kartu ATM, dan dokumen penting.'),
      _Blok(_pnt, 'Jaket, sepatu, sarung tangan, masker, helm, dan jas hujan.'),
      _Blok(_pnt, 'Tas ransel untuk membawa semuanya.'),
    ],
  ),
  _Bab(
    'Kesehatan Mental Orang Tua',
    'Mengelola emosi dan stres dalam mengasuh anak',
    Icons.self_improvement,
    [
      _Blok(_par,
          'Mengasuh anak memengaruhi kondisi emosi orang tua. Orang tua yang sehat mental mampu mengatasi stres, memberi aturan yang jelas, memahami kebutuhan anak, dan memperbaiki hubungan setelah melepas emosi berlebihan.'),
      _Blok(_sub, 'Bekerja sama dalam pengasuhan positif'),
      _Blok(_pnt, 'Ayah dan ibu bekerja sama menerapkan pengasuhan yang tegas dan penuh kasih sayang.'),
      _Blok(_pnt, 'Menyepakati aturan yang diterapkan pada anak.'),
      _Blok(_pnt, 'Tidak saling menyalahkan saat menghadapi masalah.'),
      _Blok(_sub, 'Mengenali dan mengelola emosi'),
      _Blok(_pnt, 'Kenali diri sendiri: apa yang membuat saya marah dan apa yang membuat saya lebih baik.'),
      _Blok(_pnt, 'Atur harapan dan prioritas. Jangan memaksakan semua hal saat anak sakit atau orang tua lelah.'),
      _Blok(_pnt, 'Bekerja sama dengan pasangan untuk meringankan beban.'),
      _Blok(_pnt, 'Tetap lakukan hobi untuk menjaga rasa bahagia.'),
      _Blok(_sub, 'Stres pengasuhan'),
      _Blok(_par,
          'Stres pengasuhan muncul saat orang tua merasa tidak mampu menghadapi tantangan, misalnya anak sulit makan, berat badan kurang, atau perilaku tidak sesuai.'),
      _Blok(_pnt, 'Kelola stres dengan baik, misalnya dengan relaksasi.'),
      _Blok(_pnt, 'Cari bantuan tenaga kesehatan di Puskesmas jika stres mengganggu kehidupan sehari-hari.'),
      _Blok(_pen, 'Orang tua yang terjaga kesehatan mentalnya mampu membentuk keluarga yang tangguh dan anak yang sehat.'),
    ],
  ),
  _Bab(
    'Anak dengan Disabilitas',
    'Dukungan bagi anak dan keluarga',
    Icons.accessible_forward,
    [
      _Blok(_par,
          'Anak dengan disabilitas rentan terhadap masalah kesehatan karena lebih berisiko mengalami kekerasan, hambatan pemenuhan gizi, dan ketidakmampuan memelihara kebersihan diri.'),
      _Blok(_sub, 'Yang dapat dilakukan orang tua dan keluarga'),
      _Blok(_pnt, 'Menguatkan mental untuk menerima kondisi anak.'),
      _Blok(_pnt, 'Melindungi dan memberi rasa aman dengan kasih sayang, semangat, dan motivasi.'),
      _Blok(_pnt, 'Mengajari anak dengan sabar agar mandiri dalam aktivitas sehari-hari.'),
      _Blok(_pnt, 'Menyediakan makanan bergizi seimbang dan memeriksakan kesehatan serta tumbuh kembang secara teratur.'),
      _Blok(_pnt, 'Kontrol teratur untuk terapi, pemantauan status gizi, kemajuan perkembangan, dan melengkapi imunisasi di Puskesmas terdekat.'),
      _Blok(_pnt, 'Untuk anak dengan gangguan bicara dan bahasa: latih melafalkan huruf, suku kata, kata, dan kalimat, serta melatih anak memperhatikan dan mendengarkan.'),
      _Blok(_sub, 'Dukungan komunitas'),
      _Blok(_pnt, 'Bergabung dengan komunitas orang tua atau organisasi masyarakat untuk anak dengan disabilitas.'),
      _Blok(_pnt, 'Bagi keluarga yang jauh dari komunitas, libatkan diri dalam kegiatan Posyandu, PAUD, PKK, Polindes atau Poskesdes, dan Puskesmas terdekat.'),
    ],
  ),
  _Bab(
    'Mengukur Lingkar Lengan Atas (LiLA)',
    'Skrining gizi anak usia 6-59 bulan',
    Icons.straighten,
    [
      _Blok(_par,
          'Anak usia 6-59 bulan diukur LiLA untuk skrining, deteksi dini, dan rujukan masalah pertumbuhan. Di fasilitas kesehatan, tenaga kesehatan akan mengonfirmasi dengan berat badan, panjang atau tinggi badan, dan indeks massa tubuh.'),
      _Blok(_sub, 'Cara mengukur'),
      _Blok(_pnt, 'Ukur pada lengan yang tidak terlalu aktif.'),
      _Blok(_pnt, 'Dapat dilakukan orang tua atau pengasuh terlatih di rumah, atau kader dan tenaga kesehatan terlatih setiap bulan di Posyandu.'),
      _Blok(_sub, 'Hasil pengukuran'),
      _Blok(_pnt, 'Gizi baik: lebih dari 12,4 cm.'),
      _Blok(_pnt, 'Gizi kurang: 11,5-12,4 cm.'),
      _Blok(_pnt, 'Gizi buruk: kurang dari 11,5 cm.'),
      _Blok(_pen, 'Jika hasil menunjukkan gizi kurang atau gizi buruk, harus dilakukan pemeriksaan lanjutan oleh tenaga kesehatan.'),
    ],
  ),
  _Bab(
    'Panduan Penggunaan Aplikasi',
    'Cara memakai fitur aplikasi untuk orang tua',
    Icons.phone_android_outlined,
    [
      _Blok(_sub, '1. Lengkapi data keluarga'),
      _Blok(_par,
          'Di beranda, ketuk "Lengkapi Sekarang" lalu isi data diri, data ayah, dan data anak. Data boleh disimpan bertahap.'),
      _Blok(_sub, '2. Daftar posyandu'),
      _Blok(_pnt, 'Pendaftaran dibuka 7 hari sebelum posyandu.'),
      _Blok(_pnt, 'Buka "Pendaftaran Posyandu", pilih anak, lalu ketuk Daftarkan.'),
      _Blok(_pnt, 'Pendaftaran dapat dibatalkan sebelum posyandu dimulai.'),
      _Blok(_sub, '3. Check-in'),
      _Blok(_pnt, 'Check-in dibuka 1 jam sebelum posyandu dimulai.'),
      _Blok(_pnt, 'Tunjukkan kode QR pada kartu digital anak kepada kader di Meja 1.'),
      _Blok(_sub, '4. Lihat hasil'),
      _Blok(_par,
          'Setelah anak diperiksa, hasil penimbangan, status gizi, dan catatan bidan akan tampil di beranda.'),
      _Blok(_sub, '5. Jadwal berubah'),
      _Blok(_par,
          'Bila admin mengubah atau membatalkan jadwal, cek kembali jadwal terbaru di beranda.'),
      _Blok(_pen, 'Bila mengalami kendala, tanyakan kepada kader atau bidan di posyandu.'),
    ],
  ),
];

// ---------------------------------------------------------------------------
// HALAMAN DAFTAR BAB
// ---------------------------------------------------------------------------
class BukuPanduanPage extends StatefulWidget {
  const BukuPanduanPage({super.key});

  @override
  State<BukuPanduanPage> createState() => _BukuPanduanPageState();
}

class _BukuPanduanPageState extends State<BukuPanduanPage> {
  final _cari = TextEditingController();
  String _kata = '';

  @override
  void dispose() {
    _cari.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final q = _kata.trim().toLowerCase();
    final hasil = <int>[
      for (var i = 0; i < _daftarBab.length; i++)
        if (q.isEmpty || _daftarBab[i].teksCari.contains(q)) i,
    ];

    return Scaffold(
      backgroundColor: AppColors.latar,
      appBar: AppBar(
        backgroundColor: Colors.white,
        title: const Text('Buku Panduan',
            style: TextStyle(fontWeight: FontWeight.w800, fontSize: 17)),
      ),
      body: ListView(
        padding: const EdgeInsets.fromLTRB(16, 12, 16, 24),
        children: [
          SectionCard(
            color: AppColors.hijauMuda,
            child: const Row(
              children: [
                Icon(Icons.menu_book, color: AppColors.hijau),
                SizedBox(width: 10),
                Expanded(
                  child: Text(
                    'Materi mengacu pada Buku KIA 2024 untuk orang tua. Dapat dibaca kapan saja tanpa internet.',
                    style: TextStyle(fontSize: 12),
                  ),
                ),
              ],
            ),
          ),
          TextField(
            controller: _cari,
            onChanged: (v) => setState(() => _kata = v),
            decoration: InputDecoration(
              hintText: 'Cari materi, misalnya "MP-ASI" atau "demam"',
              prefixIcon: const Icon(Icons.search),
              suffixIcon: _kata.isEmpty
                  ? null
                  : IconButton(
                      icon: const Icon(Icons.close),
                      onPressed: () {
                        _cari.clear();
                        setState(() => _kata = '');
                      },
                    ),
              filled: true,
              fillColor: Colors.white,
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: BorderSide.none,
              ),
            ),
          ),
          const SizedBox(height: 12),
          if (hasil.isEmpty)
            const Padding(
              padding: EdgeInsets.symmetric(vertical: 32),
              child: Center(
                child: Text('Materi tidak ditemukan',
                    style: TextStyle(color: AppColors.teksRedup)),
              ),
            )
          else
            for (final i in hasil) _kartuBab(i),
        ],
      ),
    );
  }

  Widget _kartuBab(int i) {
    final b = _daftarBab[i];
    final darurat = b.ikon == Icons.warning_amber_rounded;
    return Container(
      margin: const EdgeInsets.only(bottom: 10),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
      ),
      child: InkWell(
        borderRadius: BorderRadius.circular(16),
        onTap: () => Navigator.push(
          context,
          MaterialPageRoute(builder: (_) => BacaBabPage(indeks: i)),
        ),
        child: Padding(
          padding: const EdgeInsets.all(14),
          child: Row(
            children: [
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: darurat ? AppColors.merahMuda : AppColors.hijauMuda,
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Icon(b.ikon,
                    color: darurat ? AppColors.merah : AppColors.hijau, size: 26),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text('Bab ${i + 1}',
                        style: const TextStyle(
                            fontSize: 10.5,
                            fontWeight: FontWeight.w700,
                            color: AppColors.teksRedup)),
                    Text(b.judul,
                        style: const TextStyle(fontWeight: FontWeight.w800, fontSize: 14)),
                    const SizedBox(height: 2),
                    Text(b.ringkasan,
                        style: const TextStyle(fontSize: 11.5, color: AppColors.teksRedup)),
                  ],
                ),
              ),
              const Icon(Icons.chevron_right, color: AppColors.teksRedup),
            ],
          ),
        ),
      ),
    );
  }
}

// ---------------------------------------------------------------------------
// HALAMAN BACA BAB
// ---------------------------------------------------------------------------
class BacaBabPage extends StatefulWidget {
  final int indeks;
  const BacaBabPage({super.key, required this.indeks});

  @override
  State<BacaBabPage> createState() => _BacaBabPageState();
}

class _BacaBabPageState extends State<BacaBabPage> {
  late int _i = widget.indeks;
  final _scroll = ScrollController();

  void _pindah(int ke) {
    setState(() => _i = ke);
    if (_scroll.hasClients) _scroll.jumpTo(0);
  }

  @override
  void dispose() {
    _scroll.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final b = _daftarBab[_i];
    final ada = _i > 0;
    final lanjut = _i < _daftarBab.length - 1;

    return Scaffold(
      backgroundColor: AppColors.latar,
      appBar: AppBar(
        backgroundColor: Colors.white,
        title: Text('Bab ${_i + 1} dari ${_daftarBab.length}',
            style: const TextStyle(fontWeight: FontWeight.w800, fontSize: 16)),
      ),
      bottomNavigationBar: SafeArea(
        child: Container(
          color: Colors.white,
          padding: const EdgeInsets.fromLTRB(16, 10, 16, 10),
          child: Row(
            children: [
              Expanded(
                child: AppButton('Sebelumnya',
                    icon: Icons.chevron_left,
                    filled: false,
                    onPressed: ada ? () => _pindah(_i - 1) : () {}),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: AppButton(lanjut ? 'Berikutnya' : 'Selesai',
                    icon: lanjut ? Icons.chevron_right : Icons.check,
                    onPressed: lanjut ? () => _pindah(_i + 1) : () => Navigator.pop(context)),
              ),
            ],
          ),
        ),
      ),
      body: ListView(
        controller: _scroll,
        padding: const EdgeInsets.fromLTRB(16, 12, 16, 24),
        children: [
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: AppColors.hijau,
              borderRadius: BorderRadius.circular(16),
            ),
            child: Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Icon(b.ikon, color: AppColors.hijau, size: 28),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(b.judul,
                          style: const TextStyle(
                              color: Colors.white,
                              fontWeight: FontWeight.w800,
                              fontSize: 17)),
                      const SizedBox(height: 2),
                      Text(b.ringkasan,
                          style: const TextStyle(color: Colors.white70, fontSize: 11.5)),
                    ],
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 12),
          SectionCard(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [for (final blok in b.isi) _tampil(blok)],
            ),
          ),
          const Text(
            'Materi ini bersumber dari Buku KIA 2024, bersifat informasi umum, dan tidak menggantikan saran bidan atau dokter.',
            style: TextStyle(fontSize: 10.5, color: AppColors.teksRedup),
          ),
        ],
      ),
    );
  }

  Widget _tampil(_Blok b) {
    switch (b.jenis) {
      case _Jenis.subjudul:
        return Padding(
          padding: const EdgeInsets.only(top: 8, bottom: 6),
          child: Text(b.teks,
              style: const TextStyle(
                  fontWeight: FontWeight.w800, fontSize: 14, color: AppColors.hijau)),
        );
      case _Jenis.paragraf:
        return Padding(
          padding: const EdgeInsets.only(bottom: 8),
          child: Text(b.teks, style: const TextStyle(fontSize: 13, height: 1.5)),
        );
      case _Jenis.poin:
        return Padding(
          padding: const EdgeInsets.only(bottom: 6),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Padding(
                padding: EdgeInsets.only(top: 6, right: 8),
                child: Icon(Icons.circle, size: 6, color: AppColors.hijau),
              ),
              Expanded(
                child: Text(b.teks, style: const TextStyle(fontSize: 13, height: 1.5)),
              ),
            ],
          ),
        );
      case _Jenis.penting:
        return Container(
          width: double.infinity,
          margin: const EdgeInsets.symmetric(vertical: 8),
          padding: const EdgeInsets.all(12),
          decoration: BoxDecoration(
            color: AppColors.kuningMuda,
            borderRadius: BorderRadius.circular(10),
          ),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Icon(Icons.lightbulb_outline, size: 18, color: AppColors.kuning),
              const SizedBox(width: 8),
              Expanded(
                child: Text(b.teks,
                    style: const TextStyle(
                        fontSize: 12.5, fontWeight: FontWeight.w700, height: 1.4)),
              ),
            ],
          ),
        );
    }
  }
}